### ISSUE TITLE
Model architecture?

### ISSUE THREAD

**Issue by KerfuffleV2** [01-ai/Yi#1]
Hi there.

This model looks pretty interesting. Are there any details available about the model architecture so other projects (like llama.cpp) could potentially support it?

I saw your information says it was trained from scratch. Is it also a custom type of model, or does it use the same architecture as some other common model type such as LLaMA2?

**Comment by loofahcus** [comment]
We adopt llama2 model architecture, but the layernorm's names are different for our experiment purpose. 
You can refer to https://huggingface.co/01-ai/Yi-6B/blob/main/modeling_yi.py & https://huggingface.co/01-ai/Yi-6B/blob/main/config.json, and the technique report is in preparation.

**Comment by KerfuffleV2** [comment]
If you don't mind a follow-up question, this is just a base model, so there's no prompt format or anything like that to take into consideration. Is that correct?

I was able to successfully quantize it to GGUF and run inference but the results I got are a bit strange.

**Comment by loofahcus** [comment]
> If you don't mind a follow-up question, this is just a base model, so there's no prompt format or anything like that to take into consideration. Is that correct?
> 
> I was able to successfully quantize it to GGUF and run inference but the results I got are a bit strange.

Yes, it's just a base model. What's your prompt? We can study this case together.

**Comment by KerfuffleV2** [comment]
> What's your prompt? We can study this case together.

Thanks for the reply. I'll make a question in Discussions instead of continuing here so you can keep your issues on topic. (This one can be closed if you want.)
