### ISSUE TITLE
Assertion error at CUDA device

### ISSUE THREAD

**Issue by carlos-havier** [01-ai/Yi#105]
Hello,
Trying with a new conda environment created with CUDA 12.1, after installing PyTorch and all requirements, and using Yi 6B 200K by:

$python demo/text_generation.py  --model models/Yi-6B-200K

I get the following error on line 103 transformers_modules/Yi-6B-200K/modeling_yi.py of:

"Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed"

Line 103 has: hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon), and the error seems triggered by the calculation of torch.rsqrt(variance + self.variance_epsilon). But it might be false, as with Yi-32B, the line code changes (not it is accelerate/utils/operations.py", line 167, in send_to_device), but the assertion error is the same.

* Steps to reproduce:

- Install CUDA 12.1 and CuDNN on Ubuntu 20.04
- Install Anaconda
- conda create -c yi python=3.9
- conda activate yi
- git clone https://github.com/01-ai/Yi
- cd Yi
- echo "flash-attn>=2.3.3" >> requirements.txt
- pip install packaging
- pip install -r requirements.txt
- mkdir models
- cd models
- wget https://storage.lingyiwanwu.com/yi/models/Yi-6B-200K.tar
- tar xvf Yi-6B-200K.tar
- cd ..
- python demo/text_generation.py  --model models/Yi-6B-200K

**Comment by loofahcus** [comment]
same as #100, @cArlIcon
