### ISSUE TITLE
Base模型新增了tokenizer.json文件

### ISSUE THREAD

**Issue by heshuguo** [01-ai/Yi#107]
无论是6B还是34B都新增了一个tokenizer.json这个文件，这个是微调模型时必须的吗？
因为模型已经在微调中了，需要停掉并增加这个文件重新开始微调吗？

另外，有不少人再用或者微调这个模型，如果模型文件有更新的话有个小小的建议，比如有个统一的渠道告诉一下大家

**Comment by loofahcus** [comment]
这个文件不是必须的，不需要停止现有流程，谢谢。

**Comment by loofahcus** [comment]
具体增加的原因可见：#24

**Comment by ZhaoFancy** [comment]
> 另外，有不少人再用或者微调这个模型，如果模型文件有更新的话有个小小的建议，比如有个统一的渠道告诉一下大家

@heshuguo 谢谢，后期所有的更新都会以本 repo 为主，重要的内容会更新在 News section
