### ISSUE TITLE
Generation Quality and Data Source

### ISSUE THREAD

**Issue by RonanKMcGovern** [01-ai/Yi#108]
Hi folks, the generation quality of the poor is quite poor. I've tried running the 6b and the 34b models using:
```
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("01-ai/Yi-34B", device_map="auto", torch_dtype="auto", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("01-ai/Yi-34B", trust_remote_code=True)
inputs = tokenizer("There's a place where time stands still. A place of breath taking wonder, but also", return_tensors="pt")
max_length = 256

outputs = model.generate(
    inputs.input_ids.cuda(),
    max_length=max_length,
    eos_token_id=tokenizer.eos_token_id,
    do_sample=True,
    repetition_penalty=1.3,
    no_repeat_ngram_size=5,
    temperature=0.7,
    top_k=40,
    top_p=0.8,
)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```

Is this expected as the model is not chat fine-tuned?

Is further information available on the datasources and types the model was trained on?

**Comment by ZhaoFancy** [comment]
> Is this expected as the model is not chat fine-tuned?

Yes, but if you think there might be some potential bugs with our model, we can investigate it with you together.

> Is further information available on the datasources and types the model was trained on?

Not yet. This part will be explained thoroughly in our technical report. And it's estimated to be available to public the next month. You can watch our repo for the latest progress.

**Comment by RonanKMcGovern** [comment]
ok, thanks, I've emailed you to request permission to fine-tune for commercial use

**Comment by ZhaoFancy** [comment]
>  I've emailed you to request permission to fine-tune for commercial use

Cool!
Also note that, we received flood of requests in the last week. So be patient 🤗
