### ISSUE TITLE
No ignore index for pad tokens

### ISSUE THREAD

**Issue by yyhycx** [01-ai/Yi#110]
If the labels corresponding to pad tokens are not set to ignore index, how to avoid calculating loss for pad tokens?

**Comment by ZhaoFancy** [comment]
Hi @yyhycx ,

Do you mean the SFT part?

**Comment by yyhycx** [comment]
> Hi @yyhycx ,
> 
> Do you mean the SFT part?

yes

**Comment by shiyue-loop** [comment]
> If the labels corresponding to pad tokens are not set to ignore index, how to avoid calculating loss for pad tokens?

@yyhycx I believe you are right. I don't see the [`YiForCausalLM`](https://huggingface.co/01-ai/Yi-6B/blob/main/modeling_yi.py#L827-L837) ignoring the loss from padding tokens

Another question is, should we also ignore special tokens such as CLS/SEP in the loss?
