### ISSUE TITLE
Gernerated a lot of </s> when sft on 200k model

### ISSUE THREAD

**Issue by lucasjinreal** [01-ai/Yi#112]
First I thought it was my conv template problem, but after changing to using fastchat like conv template, with <|endoftext|> as splitter.

the result still got a lot of </s>

I am confused now, is that the data contains a lot of such data when training base model? 

It shouldn't happen when sft got a lot of output </s>.

It can set </s> as a badwords or token id, but this shouldn't be since it's <|endoftext|> in tokenizer.

**Comment by ZhaoFancy** [comment]
We can continue the discussion at https://github.com/01-ai/Yi/issues/80
