### ISSUE TITLE
Unable to install: missing requirements.txt file in the main branch

### ISSUE THREAD

**Issue by lvca** [01-ai/Yi#113]
It looks like the requirements.txt file is missing in the official `main` branch.

**Comment by lrx1213** [comment]
> It looks like the requirements.txt file is missing in the official `main` branch.

+1

**Comment by ZhaoFancy** [comment]
Will update the doc soon.

**Comment by shiyue-loop** [comment]
Hello @lvca and @lrx1213, I've updated the README with instructions for setting up the local development environment. You can find this information in [this section](https://github.com/01-ai/Yi#12-local-development-environment). Please give it a try.  If you encounter any issues or have questions, feel free to open a new issue or ping me directly.

**Comment by lvca** [comment]
Cool, thanks!

**Comment by lvca** [comment]
Silly question... I see your model it's available in OOLAMA models. Tried a few days ago, but it wasn't working properly. Would you suggest to use OLLAMA on a Mac to run it?

**Comment by shiyue-loop** [comment]
> Silly question... I see your model it's available in OOLAMA models. Tried a few days ago, but it wasn't working properly. Would you suggest to use OLLAMA on a Mac to run it?

@lvca We haven't experimented with OLLAMA yet, but we might consider it after future chat model releases.
