### ISSUE TITLE
规范化的api

### ISSUE THREAD

**Issue by yinjianjie** [01-ai/Yi#115]
如何部署服务，标准化openai的接口

**Comment by wangye01inf** [comment]
@yinjianjie 最新的 vllm 已经支持了 Yi 模型，可以考虑使用 VLLM 部署：https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server

**Comment by waltcow** [comment]
https://github.com/xorbitsai/inference/pull/629
