### ISSUE TITLE
训练时模型里放了 dropout 吗？

### ISSUE THREAD

**Issue by lifeiteng** [01-ai/Yi#116]
我使用 https://huggingface.co/01-ai/Yi-6B/blob/main/modeling_yi.py 来从零训练模型，指标上看 train/eval 挺不错，但 inference 时效果差了许多；
请问从零训练模型是不是应该加上 dropout？

**Comment by loofahcus** [comment]
您好，我们训练的时候并没有加上 dropout. 另外，如果你是从零训练模型，可能可以参考其他的 repo: https://github.com/NVIDIA/Megatron-LM
