### ISSUE TITLE
Whats the context window size for this 34B model?

### ISSUE THREAD

**Issue by kylehh** [01-ai/Yi#12]
The website says it supports up to 200k but a huggingface post says 32k

Whats the current models real context window size?

**Comment by zky001** [comment]
32k

**Comment by ZhaoFancy** [comment]
Apologize for the confusion. The 200k version will be released later today.

**Comment by yhyu13** [comment]
> Apologize for the confusion. The 200k version will be released later today.

wow, you guys nail it
