### ISSUE TITLE
目前的Yi-6B和Yi-34B模型支持continue-pretrain吗

### ISSUE THREAD

**Issue by zhangjiawei5911** [01-ai/Yi#120]
想用自己的语料来做一个垂直领域的大模型，想问下目前代码库里有预训练脚本吗？没找到

**Comment by ZhaoFancy** [comment]
目前暂未提供 continue training 的脚本。

**Comment by zhangjiawei5911** [comment]
> 目前暂未提供 continue training 的脚本。

预计什么时候提供或者有计划提供pretrain的脚本吗

**Comment by zhangjiawei5911** [comment]
另外6B和34B的chat版本大概什么时候能提供？

**Comment by ZhaoFancy** [comment]
> 有计划提供pretrain的脚本吗

这个我们需要内部讨论下，我打上了 `triage` 的 label，一般一周内会有回复。

**Comment by zhangjiawei5911** [comment]
> > 有计划提供pretrain的脚本吗
> 
> 这个我们需要内部讨论下，我打上了 `triage` 的 label，一般一周内会有回复。

好的感谢，期望有进展

**Comment by ZhaoFancy** [comment]
> 另外6B和34B的chat版本大概什么时候能提供？

目前已经开始了内测，所以，我只能说，快了快了 🤣

**Comment by ZhaoFancy** [comment]
目前这块没有相关的计划，建议参考其它预训练的框架。
