### ISSUE TITLE
微调代码里不同epoch没有设置train_sampler.set_epoch(epoch)不会导致不同epoch间数据一样吗

### ISSUE THREAD

**Issue by boundles** [01-ai/Yi#132]
如题，具体代码如下：

 for epoch in range(args.num_train_epochs):
        print_rank_0(
            f"Beginning of Epoch {epoch+1}/{args.num_train_epochs}, Total Micro Batches {len(train_dataloader)}",
            args.global_rank,
        )
        model.train()

**Comment by jiangchengSilent** [comment]
是的，可以考虑加入
