### ISSUE TITLE
34B模型的chat版本后期有考虑开放吗

### ISSUE THREAD

**Issue by wangqn1** [01-ai/Yi#145]
34B的模型调起来有点太费显存了，后期chat版本的会开发出来吗？

**Comment by ZhaoFancy** [comment]
会的。

参见 FAQ 第一条

https://github.com/01-ai/Yi#faq

![image](https://github.com/01-ai/Yi/assets/139539780/2c5303fe-c8cd-4852-b724-2a49989548cf)
