### ISSUE TITLE
Can this base model be used for testing?

### ISSUE THREAD

**Issue by jiqizaisikao** [01-ai/Yi#148]
Can this base model be used to test some questions to show ability? Or should I say it can only be used to fine-tune training before it can be used?

**Comment by ZhaoFancy** [comment]
Better to be used after fine-tuning. The ability to answer questions with the base model is limited.

**Comment by whgithup** [comment]
hello，When will the chat model be released？

**Comment by ZhaoFancy** [comment]
The chat models are public now.
