### ISSUE TITLE
Response Status 500 error

### ISSUE THREAD

**Issue by bilal-aamer** [01-ai/Yi#150]
Testing out the `Yi-34B` model in the playground and got the following pop-up error.

![image](https://github.com/01-ai/Yi/assets/52858537/40510665-b27e-447c-88ef-f3545f9def94)

Kindly help :)

**Comment by findmyway** [comment]
@Imccccc Could you confirm it is fixed now?

**Comment by Imccccc** [comment]
@bilal-aamer What is the URL that you used to experience this?
