### ISSUE TITLE
请问一下有MMLU、CMMLU、C-Eval等这些公开数据的评测代码吗？

### ISSUE THREAD

**Issue by cgq0816** [01-ai/Yi#153]

**Comment by coldwelldeeplove** [comment]
我们的自研eval pipeline使用与官方实现相同的方式对模型进行评测。经对比，自研eval pipeline在这几个benchmark上的结果与下面引用的官方实现一致，请参考。
MMLU：https://github.com/hendrycks/test
CMMLU：https://github.com/haonan-li/CMMLU
C-Eval：https://github.com/hkust-nlp/ceval （test集合评测需要提交结果数据，由官方评测）
