### ISSUE TITLE
保存模型的代码是不是有问题？训练完发现保存的模型文件只有1.9M

### ISSUE THREAD

**Issue by chenyzh28** [01-ai/Yi#154]
保存模型的代码是不是有问题？训练完发现保存的模型文件只有1.9M，但是没有任何报错信息。
![image](https://github.com/01-ai/Yi/assets/35193979/07475b79-628f-449b-8b20-2ae64ede11fd)
![image](https://github.com/01-ai/Yi/assets/35193979/b1a66f42-20cd-4ae8-82b3-1cb998ea4475)
![image](https://github.com/01-ai/Yi/assets/35193979/194033af-4ee3-46ad-8185-5d826b583fef)

**Comment by jiangchengSilent** [comment]
应该是你开了zero3，这里只save了部分参数，之前版本transformer的原因zero3 save出来的模型有问题所以save_zero_three函数被移除了，但最近这个问题已经被修复，我们将提一个pr来解决这个问题

**Comment by chenyzh28** [comment]
嗯嗯，之前确实是用zero3训练的，换成zero2好像可以了。希望尽快修复~

**Comment by jiangchengSilent** [comment]
jiangcheng_dev branch里边的代码已经改了，参考[https://github.com/01-ai/Yi/pull/155](url)，可以先用
