### ISSUE TITLE
在使用Yi-34b模型在C-Eval评测集上评测时发现了一个问题，无法获取scores数据信息

### ISSUE THREAD

**Issue by liu904-61** [01-ai/Yi#157]
outputs = model.generate(
        inputs.input_ids.cuda(),
        max_new_tokens=args.max_tokens,
        streamer=streamer,
        eos_token_id=tokenizer.convert_tokens_to_ids(args.eos_token),
        do_sample=True,
        repetition_penalty=1.3,
        no_repeat_ngram_size=5,
        temperature=0.7,
        top_k=40,
        top_p=0.8,
        output_scores=True,
        num_return_sequences = 1,
        use_cache = True,
        return_dict_in_generate = True,
    )
     if streamer is None:
        print(tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))
        score = outputs.scores[0]
        print(score)
       
上面是code及args信息。
但是却没有分数输出，奇怪的是decode出来的文本里，是有结果的且是正确的
![image](https://github.com/01-ai/Yi/assets/99941000/86b828af-a234-43a9-993b-9bc510c4fd8e)
![image](https://github.com/01-ai/Yi/assets/99941000/48039cac-ae12-439b-b421-b42980b489a4)

**Comment by findmyway** [comment]
能否提供完整的可复现的代码？
