### ISSUE TITLE
The model effect of 6B seems to be a bit poor, and the answer is incorrect

### ISSUE THREAD

**Issue by jkl375** [01-ai/Yi#16]
The model effect of 6B seems to be a bit poor, and the answer is incorrect
![image](https://github.com/01-ai/Yi/assets/54523287/8423573b-f4bc-40a7-928a-6ca92b664954)
![image](https://github.com/01-ai/Yi/assets/54523287/e58392a9-c30c-41f1-b76d-910e5c36421a)

**Comment by ZhaoFancy** [comment]
Hi @jkl375 ,

Thanks for reporting. Note that this is just a base model. So do expect that the generation *may* not work as expected like those after finetuning.

See also https://github.com/01-ai/Yi/discussions/5

Also note that our chat model will be released later this month. Please come back and give it a try later!

---

cc @loofahcus You might be interested in these case here.

**Comment by WindBruce** [comment]
I also found that I can not do well conversations with this model,hope to test conversation with your chat model . 
![image](https://github.com/01-ai/Yi/assets/30388825/bfc05ef5-1a7f-40e0-a21f-330aca796123)

**Comment by loofahcus** [comment]
> ersations with this model,hope to test conversation with your chat mode

As @ZhaoFancy  said, the chat model will be released late this month~

**Comment by WindBruce** [comment]
> I also found that I can not do well conversations with this model,hope to test conversation with your chat model . ![image](https://user-images.githubusercontent.com/30388825/280628367-bfc05ef5-1a7f-40e0-a21f-330aca796123.png)

I got this testing result by loading a gguf version of Yi-6B from this wesite: https://huggingface.co/SamPurkis/Yi-6B-GGUF.

**Comment by loofahcus** [comment]
Besides, GGUF may introduce BOS token which is not used in our base model, see: https://github.com/01-ai/Yi/discussions/5#discussioncomment-7484547

**Comment by ZhaoFancy** [comment]
You can try our chat models now! 🤗
