### ISSUE TITLE
Yi base 模型 tokenizer_config.json 与 chat 模型对齐？

### ISSUE THREAD

**Issue by LZHgrla** [01-ai/Yi#167]
请问可以对 base 模型的 `tokenizer_config.json` 进行修改，与 chat 模型对齐，以兼容在 chat 模型中新引入的 token（如<|im_start|>）吗？

这样将有助于其他下游微调仓库实现对 base 模型在原模版上的微调

https://huggingface.co/01-ai/Yi-34B-Chat/blob/main/tokenizer_config.json

**Comment by ZhaoFancy** [comment]
这两者本身没有依赖关系，所以不会再修改 base 模型中的 config

> 这样将有助于其他下游微调仓库实现对 base 模型在原模版上的微调

抱歉这里我没太理解为什么会对此有帮助，下游仓库如果想要在 base 模型基础上微调的话，仍然是需要根据实际情况对 config 做相应修改的。
