### ISSUE TITLE
Prompt template for chat model?

### ISSUE THREAD

**Issue by mumbledenoise** [01-ai/Yi#172]
What's the prompt template we should use for the newly released chat model? It's unclear from the demo code.

Thanks!

**Comment by Xe** [comment]
It's ChatML:

```
<|im_start|>system
{system_message}<|im_end|>
<|im_start|>user
{prompt}<|im_end|>
<|im_start|>assistant
```

**Comment by ZhaoFancy** [comment]
You can find the template at https://huggingface.co/01-ai/Yi-34B-Chat/blob/main/tokenizer_config.json#L60
