### ISSUE TITLE
safety guardrails

### ISSUE THREAD

**Issue by CelestialCoder03** [01-ai/Yi#175]
Hi I've tried the 34b-chat model on replicate and found that model safety guardrails can be bypassed quite easily with minimum adversarial prompting. The same prompt will fail on any llama chat models lol.
Here's the screenshot.
<img width="1304" alt="截屏2023-11-24 10 29 38" src="https://github.com/01-ai/Yi/assets/49389909/696f135e-87b6-4af5-8284-be044b237715">

**Comment by richardllin** [comment]
@czuo0303 

As you've pointed out, we've also recognized the issue at hand and agree that there is indeed room for improvement in this aspect of our functionality. We are committed to progressively enhancing this in our upcoming versions. 

Thank you very much for your feedback!
