### ISSUE TITLE
Do Yi-34B-Chat-Int4  support function call

### ISSUE THREAD

**Issue by Nisoka** [01-ai/Yi#181]
The chat version has been released.  Does it support function calls?  How should I build a prompt for function call.

**Comment by findmyway** [comment]
No, this version doesn't support function calls yet.

**Comment by gunpal5** [comment]
@findmyway Do you have any plan to add function call functionality? if yes, when will it be available?

**Comment by findmyway** [comment]
Hi @gunpal5 ,

Yes, we have the plan. But we do not have a clear timeline yet.

**Comment by jialinhappy** [comment]
如果基于ms-agent数据集微调之后，能支持function call吗
