### ISSUE TITLE
请问Chat模型如何进行流式回复呢？

### ISSUE THREAD

**Issue by yeyupiaoling** [01-ai/Yi#182]
官方给出的是直接返回全部结果，请问如何修改，让模型可以流式回复我的问题。

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = 'models/Yi-34B-Chat-4bits'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)

# Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cuda:0", torch_dtype='auto').eval()


# Prompt content: "hi"
messages = [{"role": "user", "content": "请扮演一个AI助手角色，你的名字叫小艺"},
            {"role": "assistant", "content": "好的，我记住了。"},
            {"role": "user", "content": "请问番茄炒蛋怎么做？"}]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True,
                                          return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

print(response)
```

**Comment by kai01ai** [comment]
如果使用HF可以参考：https://huggingface.co/docs/transformers/generation_strategies#streaming

**Comment by kai01ai** [comment]
如果有其他问题，可以reopen issue或者提新的issue

**Comment by yeyupiaoling** [comment]
嗯嗯，解决了，具体实现如下

```python
from threading import Thread

from transformers import AutoModelForCausalLM, AutoTokenizer, TextIteratorStreamer

model_path = 'models/Yi-34B-Chat-4bits'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cuda:0", torch_dtype='auto').eval()

# 对话历史
messages = [{"role": "user", "content": "请扮演一个AI助手角色，你的名字叫小艺"},
            {"role": "assistant", "content": "好的，我记住了。"},
            {"role": "user", "content": "请问番茄炒蛋怎么做？"}]

streamer = TextIteratorStreamer(tokenizer, skip_prompt=True)
input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True,
                                          return_tensors='pt')
generation_kwargs = dict(input_ids=input_ids.to('cuda'), streamer=streamer, temperature=0.95, top_p=0.8)
thread = Thread(target=model.generate, kwargs=generation_kwargs)
thread.start()
for new_text in streamer:
    new_text = new_text.replace('<|im_end|>', '\n')
    print(new_text, end="", flush=True)
```

**Comment by foreverzzx** [comment]
> 嗯嗯，解决了，具体实现如下
> 
> ```python
> from threading import Thread
> 
> from transformers import AutoModelForCausalLM, AutoTokenizer, TextIteratorStreamer
> 
> model_path = 'models/Yi-34B-Chat-4bits'
> 
> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
> model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cuda:0", torch_dtype='auto').eval()
> 
> # 对话历史
> messages = [{"role": "user", "content": "请扮演一个AI助手角色，你的名字叫小艺"},
>             {"role": "assistant", "content": "好的，我记住了。"},
>             {"role": "user", "content": "请问番茄炒蛋怎么做？"}]
> 
> streamer = TextIteratorStreamer(tokenizer, skip_prompt=True)
> input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True,
>                                           return_tensors='pt')
> generation_kwargs = dict(input_ids=input_ids.to('cuda'), streamer=streamer, temperature=0.95, top_p=0.8)
> thread = Thread(target=model.generate, kwargs=generation_kwargs)
> thread.start()
> for new_text in streamer:
>     new_text = new_text.replace('<|im_end|>', '\n')
>     print(new_text, end="", flush=True)
> ```

你好 我把这段代码发不成web 服务 然后同时两个人请求，发现收到的回复语序有点乱，推断是thread可能混在一起了，依次发请求没有问题

**Comment by yeyupiaoling** [comment]
这个应该是非线程安全的。
