### ISSUE TITLE
Cannot do demo/text_generation.py at the latest version whatever 6B or 34B

### ISSUE THREAD

**Issue by xvolica** [01-ai/Yi#185]
transformers/models/llama/modeling_llama.py:195   │
│ in forward                                                                                       │
│                                                                                                  │
│   192 │   │   bsz, q_len, _ = hidden_states.size()                                               │
│   193 │   │                                                                                      │
│   194 │   │   query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.   │
│ ❱ 195 │   │   key_states = self.k_proj(hidden_states).view(bsz, q_len, self.num_heads, self.he   │
│   196 │   │   value_states = self.v_proj(hidden_states).view(bsz, q_len, self.num_heads, self.   │
│   197 │   │                                                                                      │
│   198 │   │   kv_seq_len = key_states.shape[-2]                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: shape '[1, 14, 32, 128]' is invalid for input of size 7168

**Comment by ZhaoFancy** [comment]
Looks like a configuration error. Could you provide the code (and your environment) to produce this error?

**Comment by xvolica** [comment]
> Looks like a configuration error. Could you provide the code (and your environment) to produce this error?

I run this demo just recently, so the codes and weights are from huggingface
`
from transformers import AutoModelForCausalLM, AutoTokenizer
import os
import torch

#model_name = "Yi-6B-200K"
model_name = "Yi-34B-200K"
model_path = f'01-ai/{model_name}'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True)

# Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

inputs = tokenizer("There's a place where time stands still. A place of breath taking wonder, but also", return_tensors="pt")
max_length = 256

outputs = model.generate(
    inputs.input_ids.cuda(),
    max_length=max_length,
    eos_token_id=tokenizer.eos_token_id,
    do_sample=True,
    repetition_penalty=1.3,
    no_repeat_ngram_size=5,
    temperature=0.7,
    top_k=40,
    top_p=0.8,
)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))`

and the environment is:
NVIDIA-SMI 470.129.06  
Driver Version: 470.129.06   
CUDA Version: 11.4

**Comment by findmyway** [comment]
I can't reproduce this error. Could you try to upgrade the CUDA version  and try again?
