### ISSUE TITLE
如何使用对话能力？

### ISSUE THREAD

**Issue by dinfer** [01-ai/Yi#186]
replicate上运行01-ai/yi-34b-200k模型，想汇总新闻，但是看起来输出比预想差很多。使用默认参数。

![Screenshot_2023-11-25-09-35-43-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/01-ai/Yi/assets/11496403/77dccd5c-f7a5-4aa6-ab19-038e49ace51a)
![Screenshot_2023-11-25-09-35-51-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/01-ai/Yi/assets/11496403/66fd8441-71e7-49c7-b24f-ea3feaaef8c2)

prompt如下

---

汇总下面新闻成3句话

字节是怎么登上铁王座的？

字节已入全球牌桌
作为中国互联网大厂少数仍在保持高速增长的公司，刚刚登顶铁王座的字节是练就了钢铁之躯，还是全靠同行衬托？

毫无悬念地，一个纪录被打破了——字节跳动正式坐实了中国最赚钱的互联网公司。

11月14日，据The Information报道：字节跳动今年二季度营收达到290亿美元，同比增长约40%。以此计算，今年上半年字节总营收540亿美元（约合人民币3858亿元），远超腾讯的414亿美元。

不过如今字节已是全球牌桌上的玩家，坐在广告收入头把交椅上的Meta，今年上半年收入606亿美元，字节距其也只一步之遥。

如此惊人的收入，字节是如何做到的？The Information披露：其大部分营收来自中国市场，但增长推动主要来自TikTok。今年二季度，字节海外市场营收占比约20%，截至2023年6月，TikTok月活用户已达11亿。

字节在内容侧复制“时间熔炉”，在海内外攻城略地的同时，抖音电商的迅猛增长更让国内的电商巨头们寝食难安。

今年9月，据抖音官方披露：过去一年（2022年5月1日-2023年4月30日），抖音电商GMV增速达到80%，货架场景（抖音商城）GMV年增长超过140%。

另据「市界」从相关渠道了解：字节为抖音商城在2023年初定下了在抖音电商GMV占比中达到50%的目标。目前虽未完成，但比例已从年初的15%左右，提升到了30%；在杀入天猫、京东腹地的战斗中再下一城。

不过，字节还远未到开香槟的时候。据「市界」了解，受大环境等因素影响，抖音电商在第三季度，相较于第一、二季度几乎100%的增长，增速已经明显放缓。

10月3日，字节在一份面向员工分享的财务报告中披露：公司目前估值为2235亿美元，比照一年前已缩水约26%。今年以来，字节还在继续“降本增效”的动作，一些高投入的扩张型业务被陆续叫停。近期，字节先后传出了硬件PICO部门大幅裁员、字节游戏寻求以40亿美元价格出售沐瞳科技等消息。

在全球经济寒风之下，字节要保持领跑，还需要更多燃料。

01 字节靠什么持续赚钱？
2023年，抖音电商的凌厉表现进一步震惊了电商巨头们。随着一重重护城河被抖音打破，叠加拼多多在低线市场的攻势，最近半年来，阿里、京东频繁调整战略与组织架构，乃至更换CEO，某种程度上都与这些受迫有关。

据《晚点LatePost》报道，2023年初，抖音将GMV目标定为2.3万亿。截至今年1-10月，抖音电商已完成接近2万亿GMV，同比增速接近60%，到年底完成2.3万亿的目标已无悬念。

这样的成绩让竞争对手提心吊胆，却未见得能令字节满意。据「市界」了解，抖音电商在今年二季度增速一度超过100%，曾预计年底至少可达到2.4-2.5万亿。甚至借助年底的销售旺季，可尝试冲击3万亿GMV，实现比照2022年100%的增长。

为达宏愿，抖音并未为电商设定明确的盈利目标，仍以投入补贴为主。但下半年电商的整体疲软，还是超出了许多人的预判。

据「市界」了解，与阿里相似，现在抖音也不得不将战略目标从GMV转向了月度支付用户和订单量。希望能将商业化流量和自然流量打通，促进商家和商品的增长。

而对于阿里、京东等老牌平台来说，在抖音电商里，货架式电商的比重稳步上升，尤其让人如鲠在喉。

据「市界」了解，2021年抖音电商中商城的贡献只有不到10%，直播贡献了75%左右的GMV。而如前所述，现在商城已拿下了约30%的GMV，开始向50%的目标进发。

为了攻下这一高地，抖音可谓不遗余力。“抖音希望复制天猫品牌店规模，让商家24小时滚动在店直播。但抖音的内容化属性，让许多人更倾向于去达人直播间冲动下单，此前店播效果一直不太好。”某直播平台运营人士对「市界」说。

为此，抖音今年与一些商家签订了对赌协议。如果商家能完成一定额度的GMV以及同比例的商业化消耗，将获得不小比例的返点；借此激励商家多做自播，也能推动广告投放。

据上述人士透露，未来抖音的发展方向，商城仍是重点。“抖音与淘宝的商品数量还有近10倍的差距，抖音商城现在还是靠直播跳转、流量扶持、低价爆款、优惠券来引流。未来需要进一步完善货架，做好物流、仓储、售后的搭建。”

而在更具C端认知的直播业务上，抖音赚了多少钱，则没有商城业务那么一目了然。

由于抖音兼具“内容场”（直播间、短视频）和“货架场”（抖音商城）场景，它的交易和转化究竟由哪方牵动，并不容易厘清。但可以确定的是，前些年承担了抖音电商GMV大头的直播，比例正在逐渐下降。据《晚点LatePost》报道，今年1-10月GMV中来自“内容场”的在1.3万亿左右。

另据「市界」了解，抖音的直播业务分为电商、本地生活、秀场和综合垂类四个板块。最近，由于法规趋于严格，抖音正在加强秀场管理，但不会完全抑制直播间的发展。

而本地生活一度被抖音寄予厚望。据《晚点LatePost》报道，年初抖音给本地生活制定的目标为4000亿元。而据「市界」了解，今年上半年本地生活销售额刚刚突破了千亿元——其中由直播带来的GMV占比在30~40%之间。

不过，本地生活未达预期，也与外卖目标制定得过于激进有关。据「市界」了解，年初抖音希望外卖业务实现1000亿元，但由于各种环节未打通，日单量极少。上半年抖音便已放弃了这一目标，将目标大幅下调到了50亿。

比起上述业务，字节现在最难取得突破的反而是广告。据The Information报道，抖音预计今年在中国实现208.1亿美元的广告收入，TikTok在中国以外地区也将实现年收入200亿美元。

不过，由于前述的抖音“内容场”与“货架场”交织流动，追溯广告收入的源头，也变得不容易。

据《晚点LatePost》报道，2022年初抖音有超过 1/3 的广告收入来自于电商业务带来的 “内循环收入”。所谓“内循环”，即是商家为了卖出更多商品，在直播间或短视频渠道采购的广告。在2021年5月，这个比例还只有不到10%。另据36氪报道，从2021年3季度开始，字节的广告收入增速已开始下滑。知情人士称：“刨除电商业务的带动，字节跳动全年广告收入同比几乎没有增长。”

02 硬币的另一面
今年字节业绩的确风光，这只是硬币的一面。另一面，管理者们仍在为一些创新业务感到焦虑，首当其冲便是TikTok。如前所述，字节电商业务在GMV层面虽然猛增，但尚在投入期。伴随着实打实的广告业务触达瓶颈，The Information报道，字节40%的收入增长主要依靠的是TikTok的扩张。

但从年初开始，TikTok便在许多国家遇到了来自监管、经营层面施加的压力。

今年2月底，美国和加拿大政府宣布禁止在政府设备上使用TikTok。3月，TikTok CEO周受资出席了美国国会众议院能源和商务委员会听证会，其遭遇的连环质询，引起了业界对于TikTok前景的担忧。

▲（2023年3月23日，周受资出席听证会）

今年以来，美国对于TikTok的限制层层加码。目前，包括威斯康辛州、北卡罗来纳州、纽约市在内的美国多个州和城市都下令禁止在政府设备上使用TikTok。今年5月，蒙大拿州也成为了全美首个全面封禁TikTok的州。

据钛媒体报道，为应对监管层的挑战，字节跳动为TikTok投入了巨额游说费用。其从多家非营利机构发布的数据中发现，2022年，字节跳动在美国的游说开支达到了540万美元左右，甚至超过了华为等公司。

另一方面，Meta、Google等巨头开发的短视频“平替”产品也在加速上线。

7月，扎克伯格宣布旗下的短视频产品Reels在Facebook和Instagram上的单日播放量已超过2000亿次。Reels年化广告收入已经超过100亿美元。同期，Google在7月的二季报中表示，旗下短视频产品YouTube Shorts产品的月活用户，已从一年前的15亿增长到了20亿以上。

面对已加速布局、且先期具备全球化优势和资源的对手，TikTok需要将触角伸向更多地域，并将海外商业化进度同步提上日程。但TikTok要想复制抖音在国内的神话，搭建地方团队、适应市场与法规环境，都需要时间。

寒意阵阵之下，保持警惕与“高质量增长”，仍将是字节的主旋律。2022年底，字节跳动CEO梁汝波在公司全员会上表示，会持续地进行“去肥增痩”。梁汝波提到，公司营收增速减慢；产品DAU虽然还在增长，但低于年初设定目标的预期。

而在仍需要大举投入，但短期得不到明确回报的业务上，准备过紧日子的字节也频频做出刹车动作。

2021年8月，字节以90亿元价格收购了硬件公司PICO。据媒体统计，两年多以来，字节在PICO业务上的投入超过数百亿元。11月7日，PICO CEO周宏伟在全体员工大会上，宣布PICO将裁员300余名员工。裁员后，将保持1000余名团队规模继续运转。

另据近日路透社报道，字节也在与潜在买家会面，寻求以50亿美元价格出售旗下游戏部门沐瞳科技。

2021年3月，字节游戏曾高举高打，并以40亿美元价格拿下沐瞳科技。但最近一年，字节游戏部门朝夕光年发展不顺，始终未能产出爆款。

于今年7月暑期上线、投入高昂的《晶核》一度被视为希望，但它的流水表现也很快“由夏入秋”。根据Sensor Tower 9月发布的数据显示：短短一个月，《晶核》流水收入便已从8月的第5位滑落至11位。

一位前抖音投放BP曾对「市界」表示：字节对发行成果很看数据。朝夕光年在字节内部拿流量也需要计算ROI。“抖音把流量倒给朝夕光年，不如倒给外部游戏更赚钱。”

因此，朝夕光年负责人严授也要四处找流量，甚至要去跟腾讯谈流量合作。接下来，字节游戏将何去何从，也被画上问号。

03 腾讯忙着寻找“状态最好的人”
比起字节倾尽全力成为全行业公敌也要做大电商，刚刚被字节挤下“老大”宝座的腾讯，并没有丝毫懈怠。

11月11日，在腾讯25周年司庆上，马化腾发表了内部信，提出了腾讯新的管理理念：“让状态最好的人上场”。并在信中反复用上心、激情、入定等“发散”性词语，号召员工将产品做到极致，倾听用户的声音。

谁是状态最好的人？在信中马化腾只举了微信作例子。同时，他也提醒员工们不要做无效的投入，保持对资源使用的克制。“产品没有真正做好之前，不要滥用平台和其他资源。当用户没有自动在增长的时候，尽量不要打扰用户。乱加资源、拉营销相当于给产品加了滤镜，看不出原貌。最好是在原生态的情况下，找准方向点再发力。”

在游戏增长放缓的背景下，腾讯越来越寄希望于状态更好的微信挺身而出——在过去的三季度里，视频号中的“内循环广告”便是增长最快、也被腾讯重点拿来披露的业务之一。

11月15日，腾讯公布了2023年三季报。据财报显示：腾讯当季营收1546.25亿元，同比增长 10%；净利润449.2亿元，同比增长39%。

从营收和净利润来看，腾讯的财报表现较为平稳。但将业务进行拆解分析后，会发现腾讯的收入引擎已在暗暗切换。

在最为核心的增值服务（主要为游戏、网络广告）中，腾讯收入757.48亿，同比仅增长4%。其中，游戏收入460亿元，同比增长7%；而网络广告收入为257亿元，同比增长20%——广告成为腾讯业务中增长最快的一环。

财报会上，腾讯表示：广告能够取得显著增长，很大程度上得益于以微信小程序、视频号、公众号和企业微信为落地页的“泛内循环广告”，同比增长超30%，并贡献了超一半的微信广告收入。

腾讯首席战略官詹姆斯·米歇尔在电话会议上提及，广告业务板块毛利率从30%提高到了大约50%。是业务中增长最快的收入流，也是利润率最高的收入流。“并且我们认为利润率还有提升空间。”

腾讯披露财报后，业内普遍认为，微信与视频号已成为腾讯未来倚赖的最大增长亮点。而危墙之下仿效抖音，视频号也需要快速承担起更多的电商功能，进而帮助广告转化。腾讯集团总裁刘炽平表示：视频号的商业化仍处于早期阶段，除了打赏和广告业务外，在直播电商等层面，变现空间还很大。

毕竟腾讯曾经的“现金牛”游戏业务，正处于高度不确定当中。

虽然一方面，游戏增速总体平稳。第三季度，腾讯本土市场游戏收入增长5%至327亿元，国际市场游戏收入增长14%至133亿元——但这些增长，核心仍是由《王者荣耀》《DNF》等“长青游戏”贡献的收益。

据「市界」统计，从2021年Q4至今，在腾讯公布的8次季度财报中，游戏业务除了2023年Q3的460亿，以及2023年Q1的483亿之外，其余季度一直在420-440亿之间小幅波动——这也可以侧面说明，腾讯已经很久没有大爆款产生了。

詹姆斯·米歇尔在财报会上表示，部分游戏的研发周期拉长了6到18个月，“原因之一是公司发现表现最为优秀的游戏蕴含更大的机会，我们会更有耐心，也会花更多时间，投入更多资源同他们一道打磨游戏产品。”

“现金牛”产奶量减少，腾讯需要微信站出来分担压力，而其内部的降本增效也或将延续。

刘炽平在财报会上表示：“过去几年，中国互联网经历了结构性挑战。一个重大战略变化是，从不惜一切代价追求收入最大化转向实现高质量、可持续的增长。相信我们已经进入了一个高质量的收入增长模式，成本纪律和团队结构优化是其中的关键之一。”

但高质量、可持续的增长，对于字节、腾讯乃至整个互联网来说，都是一道不好解答的附加题。在大厂内部，不同位置亦会有不同的体感。

伴随着抖音上市仍旧没有时间表，字节内部的一些员工时常在高节奏的工作状态下略感迷茫。“公司文化还是有点卷，每天开无数的会做对齐，什么都要有ROI和数据证明。加班也让人疲惫，现在不知该再坚持一下，还是撤退。”一位抖音员工对「市界」说。

**Comment by AeroXi** [comment]
似乎yi-34b-200k-chat模型还没有发布

**Comment by ZhaoFancy** [comment]
`01-ai/yi-34b-200k` 是 base model
