### ISSUE TITLE
我对system prompt的内容有些不解，可以帮忙吗？

### ISSUE THREAD

**Issue by MaxZhongSheep** [01-ai/Yi#197]
readme里面有说到如下方法构建chat：
<|im_start|>system
{system_message}<|im_end|>
<|im_start|>user
{prompt}<|im_end|>
<|im_start|>assistant

在tokenizer的配置文件里面也有如下内容
"tokenizer_class": "LlamaTokenizer",
 "use_default_system_prompt": true
 
 但是我使用
 input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
 输出如下（并不包含system部分）
 <|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n
 
 我在transformers上面看到类似的issue（llama2）,请问我想微调chat的时候是不是也不需要system
 https://github.com/huggingface/transformers/issues/26766

**Comment by kai01ai** [comment]
当前版本的Chat Model没有默认的system message，可以与llama一样不加system message使用

**Comment by MaxZhongSheep** [comment]
> 当前版本的Chat Model没有默认的system message，可以与llama一样不加system message使用

好的谢谢回答。
