### ISSUE TITLE
34B Chat模型推理速度太慢了，这个有什么优化手段吗？

### ISSUE THREAD

**Issue by Nuclear6** [01-ai/Yi#202]
英伟达4090单卡，24G显存，推理过程中占用21G显存，prompt改为How do you evaluate the company OpenAI?
推理时间长达一下午，一度以为是程序挂了呢，最后还是输出回答了
<img width="1728" alt="image" src="https://github.com/01-ai/Yi/assets/49468241/fb17b46e-baeb-44a7-b719-b9393fc7049e">

**Comment by findmyway** [comment]
这，如果不换硬件的话，大概只能试试量化后的版本？

**Comment by bigbaldy1128** [comment]
看着是用了21G显存，实际上应该已经用到了内存了，甚至磁盘，所以特别慢，理论上34B模型需要4块24G显存的显卡
