### ISSUE TITLE
使用fachat推理Yi-34B-Chat无线输出不终止，修改了stop_str为<|im_end|>也还是不行

### ISSUE THREAD

**Issue by Malestudents** [01-ai/Yi#205]

**Comment by MarvinLong** [comment]
"eos_token": "<|endoftext|>"
------------------------------
tokenizer config 中结束字符是这个

**Comment by itsliupeng** [comment]
你指的是在 FastChat 里吗？ 
需要加一下 stop_token_ids,  https://github.com/itsliupeng/FastChat/blob/liupeng/fastchat/conversation.py#L392C17-L392C17
