### ISSUE TITLE
双4090，加载Yi-34B-Chat-4bits时间超过15分钟

### ISSUE THREAD

**Issue by hxujal** [01-ai/Yi#206]
```
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = '../models/01ai/Yi-34B-Chat-4bits'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)

# Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    load_in_4bit=True,
    device_map="auto",
    torch_dtype='auto'
).eval()

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
```

**Comment by mrhalyang** [comment]
I also encountered this problem, I think the each model file is too large.

**Comment by doublekkkkkk** [comment]
这个4bits有问题，我A100-40g用官方提供的代码加载了半小时出不来，显存只用了一点，倒是CPU内存干到六十多g了

**Comment by forpanyang** [comment]
使用 transformers==4.35.0 直接使用下面代码跑 4bit 的模型试试:
```
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = '01-ai/Yi-34b-Chat-4bits'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)

# Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
```

**Comment by forpanyang** [comment]
不需要 `load_in_4bit=True` 参数。

**Comment by hxujal** [comment]
> 使用 transformers==4.35.0 直接使用下面代码跑 4bit 的模型试试:
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> model_path = '01-ai/Yi-34b-Chat-4bits'
> 
> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
> 
> # Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
> model = AutoModelForCausalLM.from_pretrained(
>     model_path,
>     device_map="auto",
>     torch_dtype='auto'
> ).eval()
> 
> # Prompt content: "hi"
> messages = [
>     {"role": "user", "content": "hi"}
> ]
> 
> input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
> output_ids = model.generate(input_ids.to('cuda'))
> response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)
> 
> # Model response: "Hello! How can I assist you today?"
> print(response)
> ```

解决问题了，不要下载量化模型，直接加参数
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype='auto', load_in_4bit=True).eval()

**Comment by fengmy** [comment]
L40s
gptq Yi-34B-Chat-8bits   1200tokens  ~55s
awq  Yi-34B-Chat-4bits  1200tokens  ~35s
