### ISSUE TITLE
请问下怎么推理Yi-34B-200k的模型？

### ISSUE THREAD

**Issue by taishan1994** [01-ai/Yi#208]
怎么样推理才能达到200k的长度，如果GPU资源充足的情况下？

**Comment by findmyway** [comment]
请问做过哪些尝试？遇到了什么具体的问题么？

**Comment by taishan1994** [comment]
> 请问做过哪些尝试？遇到了什么具体的问题么？

在一台A800，8卡上进行推理，使用transformers库。或者您能提供一些推理的代码示例？

**Comment by findmyway** [comment]
> 或者您能提供一些推理的代码示例？

抱歉，我们这边暂时没有对外公开推理相关部分代码的计划，如果有遇到一些具体问题的话，我们可以协调相关的同学帮忙一起看下。
