### ISSUE TITLE
200K chat model performance

### ISSUE THREAD

**Issue by excellent-ai** [01-ai/Yi#209]
Could you run this long context test for `Yi-34B-200k`?

code: [link](https://github.com/gkamradt/LLMTest_NeedleInAHaystack)

The results for `GPT-4-128k` and `Claude 2.1` are as follows:
![image](https://github.com/gkamradt/LLMTest_NeedleInAHaystack/raw/main/img/GPT_4_testing.png)
![image](https://github.com/gkamradt/LLMTest_NeedleInAHaystack/raw/main/img/Claude_2_1_testing.png)

**Comment by FlyingPotatoZ** [comment]
It seems necessary, looking forward to good news！！

**Comment by Yimi81** [comment]
Please review our technical report, which reports the results of the "Needle in a Haystack" test
