### ISSUE TITLE
使用vllm运行Yi-34B-Chat-4bit错误

### ISSUE THREAD

**Issue by zh-nj** [01-ai/Yi#217]
使用vllm运行Yi-34B-Chat-4bit，python -m vllm.entrypoints.apiserver --model /media/data/Yi-34B-Chat-4bit --tensor-parallel-size 4 --quantization awq不能运行， --tensor-parallel-size 2可以运行，输出满max_tokens才会停止，短回答就重复到max_tokens停止。

**Comment by findmyway** [comment]
试下 #223 里的建议？

**Comment by yxdr** [comment]
这个原因应该是这样：虽然在应该停止时模型正确地生成了<|im_end|>这个token，但加载的tokenizer的eos_token是<|endoftext|>，vllm是以这个eos_token_id判断停止的。你可以用这个方法设置正确的停止token_id https://github.com/01-ai/Yi/issues/223#issuecomment-1864015591
