### ISSUE TITLE
demo text_generation.py script always produces a single sentence 

### ISSUE THREAD

**Issue by ujaved** [01-ai/Yi#218]
When I run `python3 text_generation.py --model 01-ai/Yi-6B --tokenizer 01-ai/Yi-6B --max-tokens 512 --eos-token $'\n'`, 
the output is always just 3-4 words. Examples:

--> "Let me tell you an interesting story about cat Tom and mouse Jerry, they are very good friends."
--> "Let me tell you an interesting story about cat Tom and mouse Jerry, who are always fighting."
--> "Let me tell you an interesting story about cat Tom and mouse Jerry, who live in a house."

why is this?

**Comment by findmyway** [comment]
I can't reproduce this. Could you try to change the `--eos-token` and see if it affects the generated results?
