### ISSUE TITLE
是否可以给一下引用格式

### ISSUE THREAD

**Issue by xieeryihe** [01-ai/Yi#219]

**Comment by liyucheng09** [comment]
可以用这么引吧
```
@misc{Yi,
      title={A series of large language models trained from scratch by developers at 01-ai}, 
      author={Yi},
    howpublished = {\url{https://github.com/01-ai/Yi}},
    year={2023}
}
```

**Comment by yuanmeng1120** [comment]
微调完，重复字符很严重，不知道谁也遇到过，要怎么解决这个问题？
![1](https://github.com/01-ai/Yi/assets/61146321/50091118-f548-4e2d-bee4-189bef46a471)
![2](https://github.com/01-ai/Yi/assets/61146321/c3cc440f-1227-4955-9bfd-4699b4e96fcf)

**Comment by xieeryihe** [comment]
prompt添加：禁止重复输入
或者prompt里面 限制输出长度
应该有一定作用

**Comment by Yimi81** [comment]
技术报告已出，可以参考[这里](https://github.com/01-ai/Yi/blob/eb01425e895cf49270420e1af507eafb41fdb222/README.md?plain=1#L1123)引用
