### ISSUE TITLE
在评测Chat的模型的时候评测指标远远低于官网指标，请问是哪里使用的不对吗？

### ISSUE THREAD

**Issue by cgq0816** [01-ai/Yi#221]
如题，使用一些公开的方法评测6B-Chat和34B-Chat模型，发现CEVAL和MMLU的指标远远低于官网，请问是哪里使用的不对吗？能否公开一下base和Chat的评测方法呢
![image](https://github.com/01-ai/Yi/assets/42534237/28b83c84-4ff5-4ccc-99c2-f358649d73d1)

**Comment by cgq0816** [comment]
> @kai01ai 帮忙看下
> 
> 另外，你方便分享下是如何自测的么？
参考Qwen的评测方法，把模型推理改成官网的推理方式
![image](https://github.com/01-ai/Yi/assets/42534237/022e76e8-ebb2-4439-9eee-a157770f8c13)

https://github.com/QwenLM/Qwen/blob/main/eval/EVALUATION.md

**Comment by kai01ai** [comment]
Hi @cgq0816 

我们的C-Eval的prompt样例如下
```text
以下是关于 高中语文 的单项选择题，请选出其中的正确答案。
下列词语的注音有错误的一项是____
A. 思量（liáng）	度量（liàng）	胸脯（pú）	果脯（fǔ）
B. 颤（zhàn）抖	颤（chàn）栗	靓（jìng）妆	靓（liàng）女
C. 阽（diàn）危	玷（diàn）辱	胡诌（zhōu）	谄（chǎn）谀
D. 瞋目（chēn）	瞠（chēng）目结舌  觊觎（yú）	面面相觑（qù）

正确答案是:
```
MMLU的prompt样例如下
```text
The following are multiple choice questions (with answers) about moral scenarios. Please select the correct answer and output the corresponding option.

For which of these two scenarios does the main character (who uses I/me/my) do something clearly morally wrong, according to ordinary moral standards in the US as of 2020? Scenario 1 | I chopped down the trees intended for lumber. Scenario 2 | While visiting the Louvre, I touched many of the paintings.
A. Wrong, Wrong
B. Wrong, Not wrong
C. Not wrong, Wrong
D. Not wrong, Not wrong

The correct answer is:
```

我们统一使用greedy的方式（temperature=0）进行生成。供参考

**Comment by findmyway** [comment]
@kai01ai 辛苦有空的时候再看下

**Comment by Sanster** [comment]
> > Hi @cgq0816
> > 我们的C-Eval的prompt样例如下
> > ```
> > 以下是关于 高中语文 的单项选择题，请选出其中的正确答案。
> > 下列词语的注音有错误的一项是____
> > A. 思量（liáng）	度量（liàng）	胸脯（pú）	果脯（fǔ）
> > B. 颤（zhàn）抖	颤（chàn）栗	靓（jìng）妆	靓（liàng）女
> > C. 阽（diàn）危	玷（diàn）辱	胡诌（zhōu）	谄（chǎn）谀
> > D. 瞋目（chēn）	瞠（chēng）目结舌  觊觎（yú）	面面相觑（qù）
> > 
> > 正确答案是:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > MMLU的prompt样例如下
> > ```
> > The following are multiple choice questions (with answers) about moral scenarios. Please select the correct answer and output the corresponding option.
> > 
> > For which of these two scenarios does the main character (who uses I/me/my) do something clearly morally wrong, according to ordinary moral standards in the US as of 2020? Scenario 1 | I chopped down the trees intended for lumber. Scenario 2 | While visiting the Louvre, I touched many of the paintings.
> > A. Wrong, Wrong
> > B. Wrong, Not wrong
> > C. Not wrong, Wrong
> > D. Not wrong, Not wrong
> > 
> > The correct answer is:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我们统一使用greedy的方式（temperature=0）进行生成。供参考
> 
> 已经换了prompt的，yi-6b-chat的指标基本上相差不大，但是yi-34b-chat ceval和gsm8k指标差距还是很大，请问该如何优化呢 ![image](https://private-user-images.githubusercontent.com/42534237/287617426-407b95b9-55bb-43ba-99d7-98fc97979295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzc5NTIsIm5iZiI6MTcwMjI3NzY1MiwicGF0aCI6Ii80MjUzNDIzNy8yODc2MTc0MjYtNDA3Yjk1YjktNTViYi00M2JhLTk5ZDctOThmYzk3OTc5Mjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA2NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMGY0YzdhZjAzMjY4OGYzMGNlZmIwZjQ1YjUwMjYyZGI0M2FiMDI4MzE1YjE0NDE2ZWVjZDk4NWRjMmM5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzxjZxRc4LOiG5L9AcaVKsPq2uaVD6cgtDljZNV2eWQ)
> 
> ceval代码如下： ![image](https://private-user-images.githubusercontent.com/42534237/287617874-84c54fc1-5e6b-4dac-8984-1fe0578585aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzc5NTIsIm5iZiI6MTcwMjI3NzY1MiwicGF0aCI6Ii80MjUzNDIzNy8yODc2MTc4NzQtODRjNTRmYzEtNWU2Yi00ZGFjLTg5ODQtMWZlMDU3ODU4NWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA2NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjMyNjMyMmY2ZTc4NzBmZTcyMDgyNjZhODNlMGRlNWJlMDM5OWM0ZGIyNGU5YTEzYTUwMjk1YjE1YTE3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkq4Ip_UhFgTBygJpgPzyMiGvH3iaQSEAsl1eOn4Kh4)

gsm8k 这么低可能是因为 fewshot prompt 的构造方式的影响，要使用多轮对话形式，以 chatml 格式为例：
```
<|im_start|>user
fewshot question1<|im_end|>
<|im_start|>assistant
fewshot answer1<|im_end|>
<|im_start|>user
fewshot question2<|im_end|>
<|im_start|>assistant
fewshot answer2<|im_end|>
.....
<|im_start|>assistant
test question<|im_end|>
<|im_start|>assistant
```

**Comment by cgq0816** [comment]
> > > Hi @cgq0816
> > > 我们的C-Eval的prompt样例如下
> > > ```
> > > 以下是关于 高中语文 的单项选择题，请选出其中的正确答案。
> > > 下列词语的注音有错误的一项是____
> > > A. 思量（liáng）	度量（liàng）	胸脯（pú）	果脯（fǔ）
> > > B. 颤（zhàn）抖	颤（chàn）栗	靓（jìng）妆	靓（liàng）女
> > > C. 阽（diàn）危	玷（diàn）辱	胡诌（zhōu）	谄（chǎn）谀
> > > D. 瞋目（chēn）	瞠（chēng）目结舌  觊觎（yú）	面面相觑（qù）
> > > 
> > > 正确答案是:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > MMLU的prompt样例如下
> > > ```
> > > The following are multiple choice questions (with answers) about moral scenarios. Please select the correct answer and output the corresponding option.
> > > 
> > > For which of these two scenarios does the main character (who uses I/me/my) do something clearly morally wrong, according to ordinary moral standards in the US as of 2020? Scenario 1 | I chopped down the trees intended for lumber. Scenario 2 | While visiting the Louvre, I touched many of the paintings.
> > > A. Wrong, Wrong
> > > B. Wrong, Not wrong
> > > C. Not wrong, Wrong
> > > D. Not wrong, Not wrong
> > > 
> > > The correct answer is:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我们统一使用greedy的方式（temperature=0）进行生成。供参考
> > 
> > 
> > 已经换了prompt的，yi-6b-chat的指标基本上相差不大，但是yi-34b-chat ceval和gsm8k指标差距还是很大，请问该如何优化呢 ![image](https://private-user-images.githubusercontent.com/42534237/287617426-407b95b9-55bb-43ba-99d7-98fc97979295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzc5NTIsIm5iZiI6MTcwMjI3NzY1MiwicGF0aCI6Ii80MjUzNDIzNy8yODc2MTc0MjYtNDA3Yjk1YjktNTViYi00M2JhLTk5ZDctOThmYzk3OTc5Mjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA2NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMGY0YzdhZjAzMjY4OGYzMGNlZmIwZjQ1YjUwMjYyZGI0M2FiMDI4MzE1YjE0NDE2ZWVjZDk4NWRjMmM5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VzxjZxRc4LOiG5L9AcaVKsPq2uaVD6cgtDljZNV2eWQ)
> > ceval代码如下： ![image](https://private-user-images.githubusercontent.com/42534237/287617874-84c54fc1-5e6b-4dac-8984-1fe0578585aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzc5NTIsIm5iZiI6MTcwMjI3NzY1MiwicGF0aCI6Ii80MjUzNDIzNy8yODc2MTc4NzQtODRjNTRmYzEtNWU2Yi00ZGFjLTg5ODQtMWZlMDU3ODU4NWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA2NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjMyNjMyMmY2ZTc4NzBmZTcyMDgyNjZhODNlMGRlNWJlMDM5OWM0ZGIyNGU5YTEzYTUwMjk1YjE1YTE3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qkq4Ip_UhFgTBygJpgPzyMiGvH3iaQSEAsl1eOn4Kh4)
> 
> gsm8k 这么低可能是因为 fewshot prompt 的构造方式的影响，要使用多轮对话形式，以 chatml 格式为例：
> 
> ```
> <|im_start|>user
> fewshot question1<|im_end|>
> <|im_start|>assistant
> fewshot answer1<|im_end|>
> <|im_start|>user
> fewshot question2<|im_end|>
> <|im_start|>assistant
> fewshot answer2<|im_end|>
> .....
> <|im_start|>assistant
> test question<|im_end|>
> <|im_start|>assistant
> ```
官方提供的指标里有zeroshot指标，测试的时候是以zeroshot做的，并不是fewshot
![image](https://github.com/01-ai/Yi/assets/42534237/e0899586-f8ff-4923-a611-a12bb21dce61)

**Comment by ShadowTeamCN** [comment]
这个issue还有下文么

**Comment by kai01ai** [comment]
Hi @cgq0816 @ShadowTeamCN 

抱歉没有及时回复

指标不匹配可能是解析规则的不同导致的，我们使用的规则包括首字母匹配、答案匹配、正则匹配等等。我们认为Chat Model的目标主要是给人类交互使用，因此在Prompt没有限制输出格式的情况下，各种输出格式只要能够被阅读理解且正确，都会认为是正确的。因此我们有一套比较复杂的答案解析过程。

**Comment by ShadowTeamCN** [comment]
> Hi @cgq0816 @ShadowTeamCN
> 
> 抱歉没有及时回复
> 
> 指标不匹配可能是解析规则的不同导致的，我们使用的规则包括首字母匹配、答案匹配、正则匹配等等。我们认为Chat Model的目标主要是给人类交互使用，因此在Prompt没有限制输出格式的情况下，各种输出格式只要能够被阅读理解且正确，都会认为是正确的。因此我们有一套比较复杂的答案解析过程。

感谢回复,请问解析脚本能方便开源到项目里么
