### ISSUE TITLE
01-ai/Yi-34B-Chat never stops with vLLM

### ISSUE THREAD

**Issue by tonyqinatcmu** [01-ai/Yi#223]
I am trying to deploy Yi-34B-Chat with vLLM, but encountered the following problem: It acts like chat model, but never stops until finish_reason "length".

The detailed information is here:

[https://github.com/vllm-project/vllm/issues/1861]

Could anyone help check this? We are looking forward to utilizing latest Yi-34B-Chat model in financial investment area.

**Comment by pseudotensor** [comment]
That worked!

**Comment by tangsipeng** [comment]
> stop_token_ids

can you tell me more how to add stop_token_ids ? 
is it possible to use vllm.entrypoints.openai.api_server  command ?

**Comment by rangehow** [comment]
> > stop_token_ids
> 
> can you tell me more how to add stop_token_ids ? is it possible to use vllm.entrypoints.openai.api_server command ?

sampling_params = SamplingParams(temperature=0.6, top_p=0.8,stop_token_ids=[7],max_tokens=1024)

**Comment by simcheuk** [comment]
In case anyone needs to do it with the openai and langchain versions:

openai
```
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "How are you?",
        }
    ],
    model="01-ai/Yi-34B-Chat",
    temperature=0.3,
    extra_body={"stop_token_ids": [7]},
)
```

langchain
```
from langchain_community.llms.vllm import VLLMOpenAI
llm = VLLMOpenAI(
    model="01-ai/Yi-34B-Chat",
    openai_api_key="EMPTY",
    openai_api_base={XXXXX},
    temperature=0.3,
    max_tokens=2048,
    model_kwargs={"extra_body": {"stop_token_ids": [7]}},
)
```
