### ISSUE TITLE
401 Client Error: Unauthorized for url: https://huggingface.co/01-ai/Yi-6B-Chat-4bits/resolve/main/config.json

### ISSUE THREAD

**Issue by avadasma** [01-ai/Yi#226]
Repository Not Found for url: https://huggingface.co/01-ai/Yi-6B-Chat-4bits/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

**Comment by findmyway** [comment]
Thanks for reporting. Should be accessible now.
