### ISSUE TITLE
请教一下，Yi-34B-chat模型 微调的数据格式是什么？

### ISSUE THREAD

**Issue by zhouyanggang** [01-ai/Yi#229]

**Comment by findmyway** [comment]
如果是用示例代码中的微调，可以参考 https://github.com/01-ai/Yi/blob/main/finetune/yi_example_dataset/data/eval.jsonl

如果是特指 `Yi-34B-Chat` 系列模型，其数据格式可以参考模板 https://huggingface.co/01-ai/Yi-34B-Chat/blob/main/tokenizer_config.json#L60
