### ISSUE TITLE
实际效果远达不到榜单评测预期效果

### ISSUE THREAD

**Issue by Minami-su** [01-ai/Yi#234]
附上一位国外ai博主的评测:https://www.youtube.com/watch?v=On3Zuv27V3k&t=1s
可以从视频评测中看到，同样的指令数据ehartford/dolphin-2_2-yi-34b的表现远不如相同训练数据的ehartford/dolphin-2.2.1-mistral-7b，就是说使用了完全相同的指令数据进行训练，仅仅只是模型的不同，测评表现就远不如open_llm_leaderboard分数更低的mistral-7b
这已经可以说明了模型的问题，然而YI 34b的open_llm_leaderboard评测结果是比mistral-7b高很多的，是否存在刷榜？我想应该是存在的
![image](https://github.com/01-ai/Yi/assets/76865636/8a057916-52e5-4510-994b-bad43a41a2f4)
![image](https://github.com/01-ai/Yi/assets/76865636/32c0edbf-8e40-4998-871a-841d3034fc49)
![image](https://github.com/01-ai/Yi/assets/76865636/9eac808e-c380-4575-8f84-2cfbabc6e9f5)

**Comment by findmyway** [comment]
> 就是说使用了完全相同的指令数据进行训练，仅仅只是模型的不同，测评表现就远不如open_llm_leaderboard分数更低的mistral-7b
> 这已经可以说明了模型的问题

这里因果关系并不直接成立。即便使用完全相同的指令数据训练，不同模型，在指令微调过程中的参数也是需要根据实际情况修改的，此外，生成过程中的一些参数对最终结果也有较大的影响，并非简单地通过替换 base model 就能做横向对比。

关于该视频内的一些 bad case 的回应，可以参考 https://github.com/01-ai/Yi/issues/189
