### ISSUE TITLE
Tokenizer class YiTokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by glaudiston** [01-ai/Yi#235]
Trying to run the model with transformers:
```
.conda/envs/synchrogpt/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 765, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class YiTokenizer does not exist or is not currently imported.
make: *** [Makefile:35: run] Error 1
```
Which package or dependency version should I ensure here to have it working?

**Comment by findmyway** [comment]
It seems you are using an old version of Yi base model. Update the model and try again?

**Comment by findmyway** [comment]
> Can you suggest one that runs in an RTX-4090 (24G VRAM)? (looking for 200K context)

I'm not aware of such model yet. `200K` is kind of special and we haven't fully evaluated the performance of those base model yet. Please watch our repo for the latest news. We may release the 200K chat version in the future.
