### ISSUE TITLE
'LlamaTokenizerFast' object has no attribute 'apply_chat_template'

### ISSUE THREAD

**Issue by lrx1213** [01-ai/Yi#241]
<img width="1542" alt="image" src="https://github.com/01-ai/Yi/assets/19346545/3d356702-1b99-43bc-be16-2cc73a9d3983">

**Comment by nicholaslike** [comment]
Can you share a snippet of your code. It looks like you are using huggingface for the tokeniser and my snippet below appear to work fine.
```
from transformers import AutoTokenizer

data = [
    {"role": "user", "content": "message 1"},
    {"role": "assistant", "content": "message 2"},
    {"role": "user", "content": "message 3"},
]
tokeniser = AutoTokenizer.from_pretrained("01-ai/Yi-34B-Chat")
chat_data = tokeniser.apply_chat_template(data, tokenize=False)
print(chat_data)

---
<|im_start|>user
message 1<|im_end|>
<|im_start|>assistant
message 2<|im_end|>
<|im_start|>user
message 3<|im_end|>
```

I am using the following package versions, these should be all the ones necessary to instantiate a the tokeniser:
```
huggingface-hub    0.19.4
Jinja2             3.1.2
protobuf           4.25.1
sentencepiece      0.1.99
transformers       4.35.2
```

**Comment by clm971910** [comment]
me tooo

**Comment by clm971910** [comment]
Traceback (most recent call last):
  File "/home/admin/yewang/test.py", line 22, in <module>
    input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
AttributeError: 'LlamaTokenizer' object has no attribute 'apply_chat_template'

**Comment by findmyway** [comment]
Please check the version of `transformers` and make sure it is `4.35.0` or above.

**Comment by linpan** [comment]
Please check the version of transformers and make sure it is 4.35.0 or above.

**Comment by AlexGao1213** [comment]
my `transformers` version: 4.39.3, but its still not work, pls help.

**Comment by linpan** [comment]
> my `transformers` version: 4.39.3, but its still not work, pls help.

del  old env , create new one . try again. plz
