### ISSUE TITLE
Yi-34B-Chat生成超参数问题

### ISSUE THREAD

**Issue by zh25714** [01-ai/Yi#244]
您好，我试用了您们发布的Yi-34B-Chat huggiface space[1]，在我的任务上比较理想，我想请问您们在这个网页上使用的生成超参数是多少呢？我有注意到您们在另一个网站上发布的demo是有默认超参数的[2]，是它们吗？

另外想请教一下，我的任务是根据示例，LLM作为Agent进行工具使用的规划，生成较为准确的测试用例，生成超参数的策略应该是怎么样的呢

万分感谢

[1]https://huggingface.co/spaces/01-ai/Yi-34B-Chat
[2]https://replicate.com/01-ai/yi-34b-chat

**Comment by findmyway** [comment]
> 请问您们在这个网页上使用的生成超参数是多少呢？

这个参数与我们在网站 README 上推荐的参数一致。

> 在另一个网站上发布的demo是有默认超参数的[2]，是它们吗？

不是的，推荐使用 README 上的参数设置 https://github.com/01-ai/Yi?tab=readme-ov-file#31-use-the-chat-model
