### ISSUE TITLE
Minimum gpus for continuous training with Yi-34B?

### ISSUE THREAD

**Issue by chuan298** [01-ai/Yi#246]
Hi team,
Thanks for your great repo, I want to continue pretraining Yi-34 with my domain dataset but I get OOM error, so I want to ask about minimum gpus to do this.
My hardware is 8 * A100 80GB and I used flash_attn, batch_size=1, max_sequence_len=4096.
Thank you.

**Comment by findmyway** [comment]
Hi @chuan298 ,

It mainly depends on the training framework and parameters you set. 

> My hardware is 8 * A100 80GB

You might consider adding more gpus if you want to do some serious work.

**Comment by Fred199683** [comment]
请问你用8张A100微调成功了吗？ @chuan298

**Comment by chuan298** [comment]
@Fred199683 yes, I can full fine-tuning with batch_size=1, flash_attn and deepspeed zero3 but it's too slow. So if you only have 8*A100, I recommend that you fine-tune with qLora or Lora.

**Comment by chuan298** [comment]
@Fred199683 I used llama factory https://github.com/hiyouga/LLaMA-Factory, a great repo
