### ISSUE TITLE
OpenLLMLeaderboard上Chat系列的成绩是不是有bug？

### ISSUE THREAD

**Issue by yucc-leon** [01-ai/Yi#247]
![image](https://github.com/01-ai/Yi/assets/17897916/1e217a2c-d991-488d-af39-75b3878c7ea5)

这里面GSM8K比首页的表格低了很多。要不要跟他们做下对齐测试？毕竟Yi的效果大家还是普遍认可的，不刷个排名有点可惜（笑）

**Comment by findmyway** [comment]
@kai01ai 可以看下？

**Comment by kai01ai** [comment]
Hi @yucc-leon 感谢反馈

1. 我们当前版本的模型对于prompt敏感性比较高，不同的prompt格式性能差异会比较大，这个是我们正在解决的问题
2. 我们在 benchmark 上的评估结果只用来保证我们的对齐训练不会损害 base 模型的基础知识和能力，我们不会以提升 benchmark 为目标来定向优化我们的 Chat 模型。
