### ISSUE TITLE
Yi-34B lora微调，8卡L40(45GB)  OOM超显存

### ISSUE THREAD

**Issue by qy1026** [01-ai/Yi#249]
Yi-34B  lora微调，8卡L40(45GB)
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 deepspeed main.py \
	--data_path /DATA_PATH/ \
	--model_name_or_path /MODEL_PATH/ \
	--per_device_train_batch_size 1 \
	--per_device_eval_batch_size 1 \
	--max_seq_len 1024 \
	--learning_rate 2e-6 \
	--weight_decay 0. \
	--num_train_epochs 4 \
	--training_debug_steps 20 \
	--gradient_accumulation_steps 1 \
	--lr_scheduler_type cosine \
	--num_warmup_steps 0 \
	--seed 1234 \
	--gradient_checkpointing \
	--zero_stage 2 \
	--deepspeed \
	--offload \
	--lora_dim 128 \
	--lora_module_name "layers." \
	--output_dir ./output_Yi_6b_chat_sft_lora
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 98 MiB. (GPU 0; 44.32GiB total capacity; 9.29 GiB already allocated; 41.00 MiB free; 9.29 GiB reserved in total by PyTorch) If reserved memory >>  allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

所以Yi-34B lora微调的最低配置是什么？

**Comment by findmyway** [comment]
@jiangchengSilent 有空的时候测试下？

**Comment by jiangchengSilent** [comment]
你好，你使用的这个脚本，在CUDA_VISIBLE_DEVICES=0,1,2,3的情况下，在A卡实测显存需要接近80G
CUDA_VISIBLE_DEVICES=0-7，内存会溢出

**Comment by qy1026** [comment]
谢谢您的解答，您的意思是，该脚本所需的显存是80G左右，对吗？但是我8卡L40，总显存是8*45GB，为什么还会超显存呢？

**Comment by jiangchengSilent** [comment]
> 谢谢您的解答，您的意思是，该脚本所需的显存是4x80G左右，对吗？但是我8卡L40，总显存是8x45GB，为什么还会超显存呢？

我的意思是单卡消耗80G左右，显存总量是不能这么换算的，一张卡的显存不能和其它卡共享。Deepspeed是通过zero、offload这些技术压低显存，但目前34b训练很难把单卡的显存压低到45GB这个水平。

**Comment by ArlanCooper** [comment]
请问一下，34b-chat是否支持lora微调呢？
