### ISSUE TITLE
Languages in the pretrain

### ISSUE THREAD

**Issue by averkij** [01-ai/Yi#25]
你好 🖐️

Did you explicitly filter other languages (non English and non Chinese) from the pretrain dataset?

If not, what are proportions of them?

**Comment by renxiaoyi** [comment]
Yes, we explicitly filtered other languages in the training dataset of this model.

**Comment by averkij** [comment]
有点伤感

**Comment by chuan298** [comment]
@ZhaoFancy  Do you have any plans to build a multilingual model?

**Comment by ZhaoFancy** [comment]
> @ZhaoFancy Do you have any plans to build a multilingual model?

Yes, we've been working on it. But we not have a clear timeline on when to release it to public.
