### ISSUE TITLE
transformers中GPTQConfig量化的dataset无法下载ConnectionError: Couldn't reach 'wikitext' on the Hub (ConnectTimeout)

### ISSUE THREAD

**Issue by pihang** [01-ai/Yi#253]
如何在安全上网的前提下执行quant_auogptq.py的量化，主要是dataset不能自动下载，本地如何加载使量化成功呢？

**Comment by findmyway** [comment]
wikitext 在 gptq 中是通过 datasets 下的 load_dataset 下载的，你可以手动离线下载并缓存在本地并配置好相关环境变量。具体请参考 datasets的文档。
