### ISSUE TITLE
微调完很多重复字符问题

### ISSUE THREAD

**Issue by yuanmeng1120** [01-ai/Yi#258]
![1](https://github.com/01-ai/Yi/assets/61146321/d77c2732-fbda-4397-8fb0-cb708c2cdbf1)
![2](https://github.com/01-ai/Yi/assets/61146321/f811c333-6b0d-451d-835c-9162b95e328f)
微调完全是这种的重复字符

**Comment by findmyway** [comment]
检查下 stop token 等参数的设置

**Comment by yuanmeng1120** [comment]
"stop token ids" : [7]  还是重复
