### ISSUE TITLE
请问yi模型支持function call的功能吗？

### ISSUE THREAD

**Issue by cgq0816** [01-ai/Yi#259]
如果支持，工具的格式是什么样的？同时想问一下支持function call的微调吗？训练语料格式是什么样的？

**Comment by findmyway** [comment]
目前暂不支持。

**Comment by cgq0816** [comment]
> 目前暂不支持。

什么时候支持呢

**Comment by findmyway** [comment]
> > 目前暂不支持。
> 
> 什么时候支持呢

目前没有明确的时间表，可以 watch 我们的 repo，有更新的时候会第一时间在这里同步。
