### ISSUE TITLE
gptq量化oom

### ISSUE THREAD

**Issue by LiuChen19960902** [01-ai/Yi#261]
请问使用auto-gptq量化时候，怎么可以多卡量化。使用官方给的脚本，尽管device_map=“auto”，但是主要执行还是在一张卡上面，量化34B模型时候会oom，想请教一下有没有什么措施可以避免。感谢~

**Comment by findmyway** [comment]
此类问题可以直接向 https://github.com/PanQiWei/AutoGPTQ/issues  反馈，我们这边暂时没有更好的建议。
