### ISSUE TITLE
eos_token is <|endoftext|>, but got </s> when decoding

### ISSUE THREAD

**Issue by shihanmax** [01-ai/Yi#262]
same question like [issue 80](https://github.com/01-ai/Yi/issues/80), I added `tokenizer.eos_token_id` to the end of the response input ids, but I got a \</s\> token after the answer, why tokenizer.eos_token not taking effect at the SFT procdure?

```
...
如果根据以上信息无法确定，请输出“未知”。你的结果是：<|im_end|> 
<|im_start|> assistant
180天</s>2017年4月25日，中国证监会发布《关于开展创新企业境内发行股票或存托凭证试点的若干意见》，并明确试点企业标准，试点企业要求“属于互联网、大数据、云计算、人工智能、软件和信息技术服务五大行业，且市值不低于2000亿元”。</s>2021年10月自考《管理学原理》模拟试题（5）
1[单选题] 管理学研究的管理过程的目的是（ ）。
A.指导管理实践
B.为管理实践提供理论依据
C.为管理实践提供决策依据
D.指导管理实践，为管理实践提供理论依据，为管理实践提供决策依据</s>1.下列关于管理学基本原理的说法，正确的是（ ）。
A.管理的目的是提高效率
...
```

**Comment by findmyway** [comment]
Better to continue discussions at #80 

By the way, you should provide more context for others to help you. Like,

- How did you generate the response above?
- What you've done to try to solve this problem?
- What's your expected result?
