### ISSUE TITLE
为啥古文的出处会出错了

### ISSUE THREAD

**Issue by yanite** [01-ai/Yi#264]
![1703073262241](https://github.com/01-ai/Yi/assets/5064763/ffe783d5-2ace-4c67-bcca-206176abab7a)
 
gpt-3.5也是错的， 目前好像是 讯飞和文心一言的正确率比较高， 

想问下， 这个是不是要微调啊？能做到  出处　１００％正确吗

**Comment by itsliupeng** [comment]
试了下 GPT-4, 错的比较离谱
不清楚 讯飞和文心一言没有开源，不清楚本身服务是否做了 RAG 检索增强
微调，如果数据配比和 instruction 得当，应该可以正确率很高，但是需要反复实验，不如做一层 RAG 简单直接
