### ISSUE TITLE
就不能在官网挂一个体验的链接吗

### ISSUE THREAD

**Issue by lmxin123** [01-ai/Yi#265]
就不能在官网挂一个体验的链接吗？找了半天，官网，公众号，开源社区等等，连一个体验链接都找不到。你们官方部署一个体验的环境没那么难吗？

我这边正好有客户需要处理长上下文本的需求，总不能每个要体验的人都自己去部署吧

**Comment by vidddddaaaaa** [comment]
他们在HF上有一个这个用着还不错 https://huggingface.co/spaces/01-ai/Yi-34B-Chat
