### ISSUE TITLE
用示例代码，返回值不符合预期。

### ISSUE THREAD

**Issue by linpeisensh** [01-ai/Yi#269]
用示例代码：
```
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = 'Yi-6B'

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)

# Since transformers 4.35.0, the GPT-Q/AWQ model can be loaded using AutoModelForCausalLM.
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
```
返回如下
![image](https://github.com/01-ai/Yi/assets/52672986/0f24a68f-7788-40fe-8fe8-cfd0f5984403)
修改
`output_ids = model.generate(input_ids.to('cuda'), max_new_tokens=200)`
返回如下
![image](https://github.com/01-ai/Yi/assets/52672986/be5c488f-4de3-49fe-a1bc-e34c763f33fa)

下载使用
```
from modelscope import snapshot_download
model_dir = snapshot_download('01ai/Yi-6B')
```
环境配置如下：
accelerate==0.25.0
addict==2.4.0
aiohttp==3.9.1
aiosignal==1.3.1
aliyun-python-sdk-core==2.14.0
aliyun-python-sdk-kms==2.16.2
async-timeout==4.0.3
attrs==23.1.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
crcmod==1.7
cryptography==38.0.4
datasets==2.14.5
Deprecated==1.2.14
dill==0.3.7
dnspython==2.4.2
einops==0.7.0
filelock==3.13.1
frozenlist==1.4.1
fsspec==2023.6.0
gast==0.5.4
gevent==21.12.0
greenlet==1.1.3.post0
grpcio==1.60.0
gunicorn==20.1.0
huggingface-hub==0.20.1
idna==3.6
importlib-metadata==7.0.0
ipaddress==1.0.23
Jinja2==3.1.2
jmespath==0.10.0
MarkupSafe==2.1.3
modelscope==1.10.0
mpmath==1.3.0
mprofile==0.0.15
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
networkx==3.2.1
numpy==1.26.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oss2==2.18.3
packaging==23.2
pandas==2.1.4
Pillow==10.1.0
platformdirs==4.1.0
ply==3.11
protobuf==3.20.3
psutil==5.9.7
pyarrow==14.0.2
pyarrow-hotfix==0.6
pycparser==2.21
pycryptodome==3.19.0
PyJWT==2.8.0
pyOpenSSL==22.1.0
python-dateutil==2.8.2
python-etcd==0.4.5
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
safetensors==0.4.1
schedule==1.2.1
scipy==1.11.4
sentencepiece==0.1.99
simplejson==3.19.2
six==1.16.0
sortedcontainers==2.4.0
sympy==1.12
thriftpy2==0.4.17
tokenizers==0.14.1
tomli==2.0.1
torch==1.13.0
tqdm==4.66.1
transformers==4.34.1
triton==2.1.0
typing-extensions==4.9.0
tzdata==2023.3
urllib3==1.26.18
wrapt==1.16.0
xxhash==3.4.1
yapf==0.40.2
yarl==1.9.4
zipp==3.17.0
zope.event==5.0
zope.interface==6.1
zprofile==1.0.13
辛苦帮忙看看是啥原因？感谢！

**Comment by findmyway** [comment]
> `01ai/Yi-6B`

你这里用的是 base model，换成 chat model 试下？
