### ISSUE TITLE
请问模型源码公开吗

### ISSUE THREAD

**Issue by Helmsman-Lab** [01-ai/Yi#27]
请问模型源码公开吗

**Comment by ZhaoFancy** [comment]
> 模型源码

这里具体是指？训练的源码？

**Comment by kunpeng199494** [comment]
Sure！You can just load the yi model by llama code with some tiny modification abuout the class name or tensor name! You will be easy !

**Comment by ZhaoFancy** [comment]
base 模型已经修改成兼容 llama 的了，可以直接用开源的一些框架来训练
