### ISSUE TITLE
请问yi-34B-chat的模型支持更长的上下文吗？

### ISSUE THREAD

**Issue by cgq0816** [01-ai/Yi#276]
请问yi-34B-chat模型支持更长的上下文吗？
The default context window is 4k tokens.
文档里说是4k，如果超过4k，该怎么让模型支持呢，还是说现在模型不支持8k，16k，32K等超长的上下文？
如果支持，该怎么配置参数呢？

**Comment by findmyway** [comment]
目前暂不支持

**Comment by weiminw** [comment]
> 目前暂不支持

yi 34b chat 大概什么时候能支持32k 或者200k？
