### ISSUE TITLE
The train/eval data format is different between the finetune guide and the chat model's chat template

### ISSUE THREAD

**Issue by benjaminhuo** [01-ai/Yi#280]
Finetune Guide:
![image](https://github.com/01-ai/Yi/assets/18525465/5bdfccac-c584-4ac5-9a44-22f4d47a700d)
https://github.com/01-ai/Yi/blob/main/finetune/yi_example_dataset/data/train.jsonl
https://github.com/01-ai/Yi/blob/main/finetune/utils/data/data_utils.py#L151C43-L151C64
https://github.com/01-ai/Yi/blob/main/finetune/utils/data/raw_datasets.py#L165

Chat Template:
https://huggingface.co/01-ai/Yi-6B-Chat/blob/main/tokenizer_config.json#L60
```yaml
"chat_template": "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<\|im_start\|>' + message['role'] + '\n' + message['content'] + '<\|im_end\|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<\|im_start\|>assistant\n' }}{% endif %}",
```
![image](https://github.com/01-ai/Yi/assets/18525465/c1fada24-81c3-47f6-94eb-1fb2fca99818)

**Comment by markli404** [comment]
I guess it is supposed to be different since one is a base model and the other is a chat model

**Comment by findmyway** [comment]
The finetuning code in this repo was meant to direct users how to use open source packages (deepspeed chat) to create chat models from base models. While the officially released chat models are trained by internal tools. This explains why the chat templates are different.
