### ISSUE TITLE
请教微调Yi-34B-Chat模型时context长度问题

### ISSUE THREAD

**Issue by IvoryTower800** [01-ai/Yi#282]
您好，我想微调这个Yi-34B-Chat模型，我看到当前模型config.json中的
max_position_embeddings是4096
rope_scaling是null
rope_theta是5000000.0

现在如果我想用16K长度的文本数据进行训练，微调出一个16K context的版本，
在训练之前，我需要如何调整这三个参数呢？

方案1：只将max_position_embeddings改为16384，保持rope_scaling和rope_thea不变

方案2：只将max_position_embeddings改为16384，同时将rope_scaling设置为{'type': 'linear', factor: 4.0}，保持rope_theta不变。

上面两种方式哪个对呢？请问正确的这三个参数如何配置呢？这个rope_theta不用调整吗？

非常非常感谢！

**Comment by netrookiecn** [comment]
> 如果你是想通过Position Interpolation的方式微调的话，你无需更改max_position_embeddings，正确的做法应该如下
> 
> ```python
> # 修改RoPE的position最大长度
> orig_ctx_len = getattr(config, "max_position_embeddings", None)
> if orig_ctx_len and args.model_max_length > orig_ctx_len:
>     scaling_factor = float(math.ceil(args.model_max_length / orig_ctx_len))
>     config.rope_scaling = {"type": "linear", "factor": scaling_factor}
> logger.info(f'Change model_max_length from {orig_ctx_len} to {args.model_max_length}')
> ```
> 
> model_max_length 是你想扩展的长度，通过它与原始长度计算出相应的scaling_factor，更新config传入到from_pretrain即可。 这里有一篇[博客文章](https://kaiokendev.github.io/til#extending-context-to-8k)与[论文](https://arxiv.org/pdf/2306.15595.pdf)相信可以帮助到你。

1、基于NTK-Rope是不是也比较简单  复用基座配置然后传入缩放因子就可以计算rope theta了。
if seq_len > self.max_position_embeddings:
            base = self.base * (
                (self.scaling_factor * seq_len / self.max_position_embeddings) - (self.scaling_factor - 1)
            ) ** (self.dim / (self.dim - 2)) # 计算新的base
            inv_freq = 1.0 / (base ** (torch.arange(0, self.dim, 2).float().to(device) / self.dim))
            self.register_buffer("inv_freq", inv_freq, persistent=False)
2、codellama做法：https://arxiv.org/pdf/2308.12950 直接将rope theta 改为1000000； 而 Yi的rope theta是5000000；是不是可以直接训即可。 不知道上述哪种效果更好
