### ISSUE TITLE
About the details and exciting story of the training process of the YI Foundation Model

### ISSUE THREAD

**Issue by sequoiar** [01-ai/Yi#29]
Could you please introduce the details and exciting story of the training process of the YI Foundation Model? 
People are very interested in YI AI Infra.

**Comment by ZhaoFancy** [comment]
Thanks for you interest. It will be described in our upcoming technical report. 💪

**Comment by sequoiar** [comment]
any update on it. thx.

**Comment by Yimi81** [comment]
@sequoiar https://arxiv.org/abs/2403.04652，tech report

**Comment by Yimi81** [comment]
@sequoiar https://arxiv.org/abs/2403.04652
