### ISSUE TITLE
Function Calling 功能支持计划

### ISSUE THREAD

**Issue by nemoiee** [01-ai/Yi#290]
请问后期是否会发布加入Function Calling微调后的版本？

**Comment by CairoLee** [comment]
同样关心，可以释放大量的使用场景

**Comment by nuoma** [comment]
暂时没有这个计划。不论是 function call 还是 agent 有很多的技术路线，想要达到稳定的效果需要结合你自己的业务场景进行微调能够达到很好的效果，所以我们希望看到更多社区开发者的微调。 see https://mp.weixin.qq.com/s/qeWEEmWlomjtFP5wQxUAcg
