### ISSUE TITLE
参考finetune的quickstart，但模型文件中没有modeling_yi.py啊

### ISSUE THREAD

**Issue by lvjianxin** [01-ai/Yi#293]
![image](https://github.com/01-ai/Yi/assets/14145018/7bbdcafc-f6ec-4bb5-bade-77a0feee633e)

**Comment by xffxff** [comment]
这一块的 readme 没有更新，最新的 Yi model 是不包含 `modeling_yi.py` 这个文件的，但并不影响后续 finetune 步骤

**Comment by lvjianxin** [comment]
如果我想优化下推理时的NTK插值，比如加上YaRN，不开放modeling_yi.py，在哪里改呢？
