### ISSUE TITLE
Yi-34B-Chat-4bit 无法配合langchain作为agent使用

### ISSUE THREAD

**Issue by weiminw** [01-ai/Yi#303]
我使用34B-chat和langchain 配合作为一个agent使用。
prompt如下：
```
ou are a friendly Chatbot that having a conversation with a human. You NEVER answer that you are an AI language model. If you don't know the answer truthfully say you don't have an answer. Don't make up an answer.

You should think step by step to find the answer.

TOOLS:
------

You has access to the following tools:



To use a tool, please use the following format:


Thought: Do I need to use a tool? Yes
Action: the action to take, should be one of []
Action Input: the input to the action
Observation: the result of the action


When you have a response to say to the Human, or if you do not need to use a tool, or there is not a available tool for using, you MUST use the format:


Thought: Do I need to use a tool? No
AI: [your response here]


Begin!

(You do not need to use these pieces of information if not relevant)

You MUST always respond to me in Chinese. 
If the response is not Chinese, You should translate it to Chinese.
You should think step by step.

Human: 给我一个北京冬天的旅游计划
Thought: Do I need to use a tool? Yes
Action: 查询北京冬季旅游信息
Action Input: 北京冬季旅游景点、活动、住宿推荐
Observation: 查询北京冬季旅游信息 is not a valid tool, try one of [].
Thought:
```

我发现agent 会一直尝试使用工具，无法直接回答 ，尝试改变很多prompt后也无法正常进行， 但是该prompt可以正常使用qwen-14b-chat 来作为agent。

**Comment by Yimi81** [comment]
这是因为目前的Yi-Chat模型暂不支持funcation call

**Comment by weiminw** [comment]
> 这是因为目前的Yi-Chat模型暂不支持funcation call

我在prompt中提示，如果没有工具，则直接回答，好像34bchat 没有完全遵从prompt。如何能让34bchat能严格遵从指令呢

**Comment by ice6** [comment]
+1

**Comment by younggggger** [comment]
> 这是因为目前的Yi-Chat模型暂不支持funcation call

所以，[langchain](https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community/chat_models) 里没有01的？

**Comment by Yimi81** [comment]
@younggggger 当然有，langchain又不止Agent开发

**Comment by younggggger** [comment]
> @younggggger 当然有，langchain又不止Agent开发

我发的是一个链接，那里有01的吗？

![image](https://github.com/01-ai/Yi/assets/127868785/ac0e9fa6-13ed-4d14-a1ed-f8612ff0e00b)

**Comment by Yimi81** [comment]
直接将yi模型部署成API服务，直接就可以在langchain里用了。或者直接用我们的API就行 可以参考这个https://platform.lingyiwanwu.com/docs#-faq

**Comment by younggggger** [comment]
你们可以建议langchain加到这里去啊，阿里的，kimi的都在这呢
![image](https://github.com/01-ai/Yi/assets/127868785/53185bc9-e935-4d28-a8e5-ab70d18f2e11)

**Comment by Yimi81** [comment]
好的 没问题 我后续加一下~
