### ISSUE TITLE
[Translation Task] Yi README: Introduction + Models + News

### ISSUE THREAD

**Issue by Anonymitaet** [01-ai/Yi#318]
> 该 issue 为「Yi 翻译计划」第 1 期 任务 issue，欢迎你一起参与共建呀~ 🙌

# 任务介绍

- 每篇文章需要 1 位译员与 1 位审校。

- 翻译与审校方向：英翻中

- 待译原文：Yi README:  
  - [Introduction](https://github.com/01-ai/Yi?tab=readme-ov-file#-introduction)
  - [Models](https://github.com/01-ai/Yi?tab=readme-ov-file#-models)
  - [News](https://github.com/01-ai/Yi?tab=readme-ov-file#-news)

- 翻译与审校步骤：参阅[「Yi 翻译计划」第 1 期](https://github.com/01-ai/Yi/discussions/314)。

# 任务要求

- 了解 [git 基本操作](https://www.cnblogs.com/daniel-hutao/p/open-a-pr-in-github.html)。

- 译文需要技术准确无误、表达流畅。

# 参考示例

- Translation and review: https://github.com/01-ai/Yi/pull/331

**Comment by GloriaLee01** [comment]
Please assign it to me.

**Comment by GloriaLee01** [comment]
Translation complete.

**Comment by bltcn** [comment]
assign it to me - review

**Comment by GloriaLee01** [comment]
@bltcn I have submitted the translation, please review  it 🙌 
![2401](https://github.com/01-ai/Yi/assets/156639183/82f913be-47ef-41c2-812b-bab45062942d)
