### ISSUE TITLE
[Translation Task] Yi README: Benchmark  + Who can use yi + Misc.

### ISSUE THREAD

**Issue by Anonymitaet** [01-ai/Yi#323]
> 该 issue 为「Yi 翻译计划」第 1 期 任务 issue，欢迎你参与共建呀~ 🙌

# 任务介绍

- 翻译方向：英翻中

- 待译原文：Yi README:  
  - [Benchmark](https://github.com/01-ai/Yi?tab=readme-ov-file#-benchmarks)
  - [Who can use Yi](https://github.com/01-ai/Yi?tab=readme-ov-file#-WhocanuseYi?)
  - [Misc.](https://github.com/01-ai/Yi?tab=readme-ov-file#-Misc.)

- 翻译步骤：详情参阅[「Yi 翻译计划」第 1 期](https://github.com/01-ai/Yi/discussions/314)。

# 任务要求

- 了解 [git 基本操作](https://www.cnblogs.com/daniel-hutao/p/open-a-pr-in-github.html)。

- 译文需要技术准确无误、表达流畅。

# 参考示例
- Translation and review: https://github.com/01-ai/Yi/pull/331

**Comment by vidddddaaaaa** [comment]
Please assign this to me.

**Comment by markli404** [comment]
Please assign it to me

**Comment by Cookize** [comment]
assign it to me - translation

**Comment by GloriaLee01** [comment]
@Cookize Thank you very much for your willingness to contribute to Yi! 🥳 You can start the review since the translation is complete.
