### ISSUE TITLE
About the inference issues of  Yi-VL-34B

### ISSUE THREAD

**Issue by White-Friday** [01-ai/Yi#324]
1. Is the current model a chat model?
2. Where can I find the inference demo code for the current model?

Thanks a lot

**Comment by Lukikay** [comment]
Same problem here. I tried to perform inference Yi-VL-6B using LLaVA code through [this](https://huggingface.co/01-ai/Yi-VL-6B#quick-start), but it resulted in an error:
> File "/LLaVA/llava/model/multimodal_projector/builder.py", line 52, in build_vision_projector
> raise ValueError(f'Unknown projector type: {projector_type}')
> `ValueError: Unknown projector type: mlp2x_gelu_Norm`

**Comment by poisonwine** [comment]
> Same problem here. I tried to perform inference Yi-VL-6B using LLaVA code through [this](https://huggingface.co/01-ai/Yi-VL-6B#quick-start), but it resulted in an error:
> 
> > File "/LLaVA/llava/model/multimodal_projector/builder.py", line 52, in build_vision_projector
> > raise ValueError(f'Unknown projector type: {projector_type}')
> > `ValueError: Unknown projector type: mlp2x_gelu_Norm`

https://github.com/01-ai/Yi/pull/330/files#diff-46115f00557d4c2505b889217bc5be4268055266cb44a9cc81b63be25382812f
This solves the problem.

**Comment by findmyway** [comment]
Please try the code under the `VL` folder.
