### ISSUE TITLE
Yi-34B-VL 中文效果炸裂

### ISSUE THREAD

**Issue by lucasjinreal** [01-ai/Yi#337]
![image](https://github.com/01-ai/Yi/assets/21303438/d9b0130c-9c5b-491e-91d2-450bb2bb278d)

This should be the best Chinese VL model at the moment!

![image](https://github.com/01-ai/Yi/assets/21303438/aa469373-14e2-44fc-aeee-8d30496b6bdb)

**Comment by xmy0916** [comment]
![image](https://github.com/01-ai/Yi/assets/43675899/177f9b85-a360-493a-bb9d-532105e661a9)
CUDA_VISIBLE_DEVICES=0 python single_inference.py --model-path ../Yi-VL-6B --image-file images/cats.jpg --question "Describe the cats and what they are doing in detail."
我这是真炸裂了，不知道啥情况

**Comment by lucasjinreal** [comment]
我跑的34b-vl，你这个是真炸了。
多测试几张图片，我发现Yi训练的这个多模态，在某些图片上容易炸

**Comment by xmy0916** [comment]
> 我跑的34b-vl，你这个是真炸了。 多测试几张图片，我发现Yi训练的这个多模态，在某些图片上容易炸

我试了34和6都炸了 不知道啥bug

**Comment by ericzhou571** [comment]
要笑喷了，蹲一个官方的回应

**Comment by BellaBei** [comment]
温度默认是0.2的情况下，试多次都是这样的结果吗？有改动代码和配置文件吗？

> ![image](https://private-user-images.githubusercontent.com/43675899/298945440-177f9b85-a360-493a-bb9d-532105e661a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzc5NDEsIm5iZiI6MTcwNjA3NzY0MSwicGF0aCI6Ii80MzY3NTg5OS8yOTg5NDU0NDAtMTc3ZjliODUtYTM2MC00OTNhLWJiOWQtNTMyMTA1ZTY2MWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMDJlM2YwZDQxOGI5MjE1ZjA5MjhkMmVkYjg1MTI2MWY3ZGExZDM2M2JiMGYwNTBlMjI1MzRlOGJiZTUxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jBcdkf_lkBEdt1TnOPnNNaokHc19Z48U97Mo9aa8jsg) CUDA_VISIBLE_DEVICES=0 python single_inference.py --model-path ../Yi-VL-6B --image-file images/cats.jpg --question "Describe the cats and what they are doing in detail." 我这是真炸裂了，不知道啥情况

**Comment by xmy0916** [comment]
@BellaBei 什么都没改，就是flash attn的版本装不上2.3.2，装了2.0.1

**Comment by idealwei** [comment]
同炸，很容易产生幻觉或大量重复句子

**Comment by lucasjinreal** [comment]
官方科比的图片是没有问题的，换一个其他的大概率炸，98%。
不知何故
