### ISSUE TITLE
Yi-34B-VL 这张图会胡言乱语，为何

### ISSUE THREAD

**Issue by lucasjinreal** [01-ai/Yi#344]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.10
PyTorch: 2.0.1+cu118
CUDA: 11.8
```

### Current Behavior

this image caused model output wrong short unable to understand result.

### Expected Behavior

shouldn't outputs meanless output

### Steps to Reproduce

gdf

### Anything Else?

![Hospital_Small](https://github.com/01-ai/Yi/assets/21303438/73f256df-19cc-41b8-9f1a-c3ef27addf8c)

**Comment by lucasjinreal** [comment]
![image](https://github.com/01-ai/Yi/assets/21303438/97e15cb1-9039-4532-a47d-1e4df6e0a81d)

**Comment by lucasjinreal** [comment]
No

**Comment by a2382625920** [comment]
> 不

OK, maybe there's something wrong with the model itself, or maybe there's something in the reasoning that doesn't fit the conditions

**Comment by Yimi81** [comment]
The open-source version of the VL model does not have good OCR capabilities, you can try our API
