### ISSUE TITLE
为什么Yi-34B-200K版本的模型文件大小是Yi-34B的一半？

### ISSUE THREAD

**Issue by xiaozhi007** [01-ai/Yi#35]

**Comment by xiaozhi007** [comment]
是否是因为200k版本模型参数精度调低了？

**Comment by loofahcus** [comment]
> 是否是因为200k版本模型参数精度调低了？

不是的，200K 的 safetensor 格式的模型还在上传中

**Comment by xiaozhi007** [comment]
> > 是否是因为200k版本模型参数精度调低了？
> 
> 不是的，200K 的 safetensor 格式的模型还在上传中

感谢回复！期待200k模型，这个能解决我们现在很大的问题，能够降低前置检索的压力。
