### ISSUE TITLE
使用Yi-VL的测试用例报错：ValueError: Non-consecutive added token '<unk>' found. Should have index 64000 but has index 0 in saved vocabulary.

### ISSUE THREAD

**Issue by chenyzh28** [01-ai/Yi#350]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
OS: Ubuntu 20.04
Python: 3.10
PyTorch: 2.0.1+cu118
CUDA: 11.8
transformers: 4.32.0
```

### Current Behavior

报错，无法正常推理。

### Expected Behavior

正常推理

### Steps to Reproduce

CUDA_VISIBLE_DEVICES=0 python single_inference.py --model-path ./ckpt/Yi-VL-6B --image-file images/cats.jpg --question "Describe the cats and what they are doing in detail."

### Anything Else?

<img width="758" alt="45BB848B-A389-4BCE-9073-1191C41E49B4" src="https://github.com/01-ai/Yi/assets/35193979/5d794c68-c57f-4c2a-ab7b-6ea7365ea9c0">

**Comment by chenyzh28** [comment]
更新transformers版本就可以了

**Comment by a2382625920** [comment]
我也遇到了同样的错误，请问transformers需要更新到什么版本最好，因为transformers容易和其他包冲突

> 更新transformers版本就可以了

**Comment by chenyzh28** [comment]
> 我也遇到了同样的错误，请问transformers需要更新到什么版本最好，因为transformers容易和其他包冲突
> 
> > 更新transformers版本就可以了

我是更新到4.36.0就可以了。
