### ISSUE TITLE
Error when trying to run quick start  code

### ISSUE THREAD

**Issue by sudhir2016** [01-ai/Yi#353]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS:
- Python:
- PyTorch:
- CUDA:
```

### Current Behavior

Getting this error when single_inference.py is trying to load model from HF Hub.

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../model/Yi-VL-6B'. Use `repo_type` argument if needed.

### Expected Behavior

Load should load.

### Steps to Reproduce

I was using this code provide for quick start in Google Colab free tier.

! CUDA_VISIBLE_DEVICES=0 python /content/Yi/VL/single_inference.py --model-path ../model/Yi-VL-6B --image-file images/cats.jpg --question "Describe the cats and what they are doing in detail."

### Anything Else?

Nil

**Comment by markli404** [comment]
I have successfully launched the demo in Google Colab with this line of code:

**Comment by sudhir2016** [comment]
My directory is different from yours. I used this code to set us environment.

!git clone https://github.com/01-ai/Yi.git
!cd Yi/VL
!export PYTHONPATH=$PYTHONPATH:$(pwd)
!pip install -r requirements.txt

Please suggest.

**Comment by markli404** [comment]
> !git clone https://github.com/01-ai/Yi.git
> !cd Yi/VL
> !export PYTHONPATH=$PYTHONPATH:$(pwd)
> !pip install -r requirements.txt

The `cd` command in colab notebook needs to start with `%`, so you can either try
```
!git clone https://github.com/01-ai/Yi.git
%cd Yi/VL
!export PYTHONPATH=$PYTHONPATH:$(pwd)
!pip install -r requirements.txt
```
or 
```
!git clone https://github.com/01-ai/Yi.git
!pip install -r ./Yi/VL/requirements.txt
```
Hope this solves the problem!

**Comment by sudhir2016** [comment]
Thank you. Still getting this error.
OSError: Incorrect path_or_model_id: './Yi-VL-6B'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
My directory structure is still different from yours. Sharing my notebook.
https://colab.research.google.com/drive/1jBT5BM10boMaEW5no1qfugc-_nfmmatG?usp=sharing

**Comment by markli404** [comment]
> Thank you. Still getting this error. OSError: Incorrect path_or_model_id: './Yi-VL-6B'. Please provide either the path to a local folder or the repo_id of a model on the Hub. My directory structure is still different from yours. Sharing my notebook. https://colab.research.google.com/drive/1jBT5BM10boMaEW5no1qfugc-_nfmmatG?usp=sharing

It seems like the model has not been downloaded in your notebook.
Please add a new code cell at the beginning, and run the following code:
```
!git lfs install
!git clone https://huggingface.co/01-ai/Yi-VL-6B
```
This will download the weight of the Yi-VL-6B model to your director (It takes about 5-10 minutes to download).
Then, run the remaining cells, and you should be able to see the output.

**Comment by sudhir2016** [comment]
Thank you so much @markli404 !!. It works now.
