### ISSUE TITLE
load_pretrained_model TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by DataLearnerAI** [01-ai/Yi#363]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS: Google Colab
- Python: 3.10.12
- PyTorch:2.1.0+cu121
- CUDA:12.2
```

### Current Behavior

I am trying to use Google Colab to load Yi-VL-6B model, but it throws an error: TypeError: expected str, bytes or os.PathLike object, not NoneType.

![image](https://github.com/01-ai/Yi/assets/132440409/880962d3-d531-4838-8412-c4dd2c1c77e1)

### Steps to Reproduce

```
import argparse
import os

import torch
from llava.conversation import conv_templates
from llava.mm_utils import (
    KeywordsStoppingCriteria,
    expand2square,
    get_model_name_from_path,
    load_pretrained_model,
    tokenizer_image_token,
)
from llava.model.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, key_info
from PIL import Image

model_path = "01-ai/Yi-VL-6B"
tokenizer, model, image_processor, context_len = load_pretrained_model(model_path)
```

**Comment by markli404** [comment]
> from llava.conversation import conv_templates

Would you please be more specific? I was not able to reproduce the error. Here is my screenshot:
![image](https://github.com/01-ai/Yi/assets/116385770/bfad118c-1084-4ebf-9925-54c33c804d4e)
The only thing I added here is `sys.path.append('/content/Yi/VL')` for loading packages under `Yi/VL`.

My guess is that you have changed some settings in other parts of the notebook.

**Comment by df19900725** [comment]
I saw you interrupt the downloading process manually. I only run code as follows:

1. Install Yi-VL-6B as follows:
```
!git clone https://github.com/01-ai/Yi.git
%cd Yi/VL
!ls
!pip install -r requirements.txt
```

2. Run code as follows:
```
import argparse
import os

import torch
from llava.conversation import conv_templates
from llava.mm_utils import (
    KeywordsStoppingCriteria,
    expand2square,
    get_model_name_from_path,
    load_pretrained_model,
    tokenizer_image_token,
)
from llava.model.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, key_info
from PIL import Image

model_path = "liuhaotian/llava-v1.5-7b"
tokenizer, model, image_processor, context_len = load_pretrained_model(model_path)
```

These two code sinppets is all what I have run in Google Colab. But after downloading model files. It throws error:

```
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
tokenizer_config.json: 100%
749/749 [00:00<00:00, 49.1kB/s]
tokenizer.model: 100%
500k/500k [00:00<00:00, 630kB/s]
special_tokens_map.json: 100%
438/438 [00:00<00:00, 34.1kB/s]
config.json: 100%
1.16k/1.16k [00:00<00:00, 60.3kB/s]
pytorch_model.bin.index.json: 100%
27.1k/27.1k [00:00<00:00, 1.86MB/s]
Downloading shards: 100%
2/2 [13:23<00:00, 365.24s/it]
pytorch_model-00001-of-00002.bin: 100%
9.98G/9.98G [10:07<00:00, 20.4MB/s]
pytorch_model-00002-of-00002.bin: 100%
3.54G/3.54G [03:13<00:00, 19.4MB/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-8d623603259d>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 model_path = "liuhaotian/llava-v1.5-7b"
---> 17 tokenizer, model, image_processor, context_len = load_pretrained_model(model_path)

5 frames
[/usr/lib/python3.10/posixpath.py](https://localhost:8080/#) in join(a, *p)
     74     will be discarded.  An empty last part will result in a path that
     75     ends with a separator."""
---> 76     a = os.fspath(a)
     77     sep = _get_sep(a)
     78     path = a

TypeError: expected str, bytes or os.PathLike object, not NoneType

````

**Comment by df19900725** [comment]
> > from llava.conversation import conv_templates
> 
> Would you please be more specific? I was not able to reproduce the error. Here is my screenshot: ![image](https://private-user-images.githubusercontent.com/116385770/300311224-bfad118c-1084-4ebf-9925-54c33c804d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTY3OTQsIm5iZiI6MTcwNjU5NjQ5NCwicGF0aCI6Ii8xMTYzODU3NzAvMzAwMzExMjI0LWJmYWQxMThjLTEwODQtNGViZi05OTI1LTU0YzMzYzgwNGQ0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNjM0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmQyOTFhYjY5MmY1MmIzNDE2MmY5YTRiMGI0MzM2YmE1ZmViNjdiYTVhNDMzNTIwODExNGU1ZmU3YzQwMGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h7eRn8-dHXlMcGkoKEcE-LfPdazCN1BSzGnK_G_QNTs) The only thing I added here is `sys.path.append('/content/Yi/VL')` for loading packages under `Yi/VL`.
> 
> My guess is that you have changed some settings in other parts of the notebook.

I think that if you wait for download to finish, you may have saw the error.

**Comment by markli404** [comment]
> > > from llava.conversation import conv_templates
> > 
> > 
> > Would you please be more specific? I was not able to reproduce the error. Here is my screenshot: ![image](https://private-user-images.githubusercontent.com/116385770/300311224-bfad118c-1084-4ebf-9925-54c33c804d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTY3OTQsIm5iZiI6MTcwNjU5NjQ5NCwicGF0aCI6Ii8xMTYzODU3NzAvMzAwMzExMjI0LWJmYWQxMThjLTEwODQtNGViZi05OTI1LTU0YzMzYzgwNGQ0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwNjM0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmQyOTFhYjY5MmY1MmIzNDE2MmY5YTRiMGI0MzM2YmE1ZmViNjdiYTVhNDMzNTIwODExNGU1ZmU3YzQwMGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h7eRn8-dHXlMcGkoKEcE-LfPdazCN1BSzGnK_G_QNTs) The only thing I added here is `sys.path.append('/content/Yi/VL')` for loading packages under `Yi/VL`.
> > My guess is that you have changed some settings in other parts of the notebook.
> 
> I think that if you wait for download to finish, you may have saw the error.

working on it now
