### ISSUE TITLE
VL 6B web_demo gradio api

### ISSUE THREAD

**Issue by carry-xz** [01-ai/Yi#378]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

Run web_demo.py locally and call Yi-VL-6B through the gradio api, but the result cannot be obtained. I hope the api description document is clearer

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
web_demo is only for display purposes and does not support call Yi-VL-6B through the gradio api
