### ISSUE TITLE
poor text handling

### ISSUE THREAD

**Issue by pseudotensor** [01-ai/Yi#381]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
ubuntu 20
python 3.10
torch 2.1.2
cuda 12.1
```

### Current Behavior

![296218150-50101668-0353-43d2-863d-40e845b3cfbb](https://github.com/01-ai/Yi/assets/2249614/50557128-bc2a-4450-9081-059a0c0fcc99)

### Expected Behavior

No repetition and description of image's text

### Steps to Reproduce

![image](https://github.com/01-ai/Yi/assets/2249614/0798fb7b-4dbd-4452-8676-ea91d470320a)

prompt:

```
Describe the image in detail.
```

Tried many other prompts, same kinds of failures.

**Comment by Yimi81** [comment]
The current version of the model does not have enhancements for OCR capabilities at the moment.
