### ISSUE TITLE
Yi-VL openai-api 支持

### ISSUE THREAD

**Issue by neuwangmq** [01-ai/Yi#382]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS:
- Python:
- PyTorch:
- CUDA:
```

### Current Behavior

我发现VL是没有提供openai-api接口封装脚本的，是否能够提供openai-api的接口封装代码，感觉这个标准化的接口还是比较有必要的？请问有支持计划吗？谢谢。

### Expected Behavior

谢谢

### Steps to Reproduce

谢谢

### Anything Else?

 谢谢

**Comment by Yimi81** [comment]
已实现，请更新代码，参考readme进行调用

**Comment by jun0wanan** [comment]
> 已实现，请更新代码，参考readme进行调用

您好，readme哪里有？你给的链接里面 没有说具体是什么名字欸，vl模型

**Comment by Yimi81** [comment]
https://github.com/01-ai/Yi/tree/main/VL#api 这里，vl-6B vl-34B都可以
