### ISSUE TITLE
YI-VL:  answering does not require reading text in the image

### ISSUE THREAD

**Issue by neuwangmq** [01-ai/Yi#383]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS:
- Python:
- PyTorch:
- CUDA:
```

### Current Behavior

![图片](https://github.com/01-ai/Yi/assets/14195475/4859a04d-a5d3-4d14-ab2c-43daffd07458)

如图，输入的图片和提示词，模型返回了
answering does not require reading text in the image
请问是什么问题？用其他的问句，例如：图片中有几只猫？describe the image。 返回的结果就是正常的。
请问可能是什么问题，通过采取怎样的错误能够避免这种错误输出。

### Expected Behavior

谢谢

### Steps to Reproduce

谢谢

### Anything Else?

谢谢

**Comment by markli404** [comment]
可以提供一下代码嘛

**Comment by neuwangmq** [comment]
import torch
import traceback
import os

import argparse
import sys

# 获取当前文件的绝对路径
current_file_path = os.path.abspath(__file__)
# 获取当前文件所在的文件夹路径
current_file_dir = os.path.dirname(current_file_path)

sys.path.append(current_file_dir+"/../")

import torch
from llava.conversation import conv_templates
from llava.mm_utils import (
    KeywordsStoppingCriteria,
    expand2square,
    get_model_name_from_path,
    load_pretrained_model,
    process_images,
    tokenizer_image_token,
)

from llava.model.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, key_info
from PIL import Image


model_id = 'yi/Yi-VL-6B'
revision = 'v1.0.0'

def disable_torch_init():
    """
    Disable the redundant torch default initialization to accelerate model creation.
    """
    import torch

    setattr(torch.nn.Linear, "reset_parameters", lambda self: None)
    setattr(torch.nn.LayerNorm, "reset_parameters", lambda self: None)

def load_image(image_file):
    image = Image.open(image_file).convert("RGB")
    return image

class YiVL:

    def __init__(self,model_path="models/Yi-VL-6B/",load_8bit=False, load_4bit=False):

        disable_torch_init()
        key_info["model_path"] = model_path
        get_model_name_from_path(model_path)
        self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(model_path=model_path,load_8bit=False, load_4bit=False)
        
        self.conv = conv_templates["mm_default"].copy()
        self.roles = self.conv.roles
        self.history = None
        

    def clear(self):
        self.history = None
        self.conv = conv_templates["mm_default"].copy()
        self.image_tensor = None


    def chat(self,query,temperature=0.8,max_new_tokens=1024):
        self.conv.append_message(self.conv.roles[0], query)
        self.conv.append_message(self.conv.roles[1], None)
        prompt = self.conv.get_prompt()

        input_ids = (
            tokenizer_image_token(
                prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
            )
            .unsqueeze(0)
            .to(self.model.device)
        )
        stop_str = self.conv.sep
        keywords = [stop_str]
        stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)

        with torch.inference_mode():
            output_ids = self.model.generate(
                input_ids,
                images=self.image_tensor,
                do_sample=True if temperature > 0 else False,
                temperature=temperature,
                max_new_tokens=max_new_tokens,
                use_cache=True,
                stopping_criteria=[stopping_criteria],
            )

        input_token_len = input_ids.shape[1]
        outputs = self.tokenizer.batch_decode(
            output_ids[:, input_token_len:], skip_special_tokens=True
        )[0]
        outputs = outputs.strip()
        if outputs.endswith(stop_str):
            outputs = outputs[: -len(stop_str)]
        outputs = outputs.strip()

        print(outputs)

        self.conv.messages[-1][-1] = outputs
        self.history = prompt
        return outputs,self.history
    
    
    def new_chat(self,image_path, query,temperature=0.8,max_new_tokens=1024):
        self.clear()
        
        # load image
        image = load_image(image_path)
        self.image_tensor = process_images([image], self.image_processor, self.model.config)
        self.image_tensor = self.image_tensor.to(self.model.device, dtype=torch.bfloat16)

        query = DEFAULT_IMAGE_TOKEN + "\n" + query
        self.conv.append_message(self.conv.roles[0], query)
        self.conv.append_message(self.conv.roles[1], None)
        prompt = self.conv.get_prompt()

        input_ids = (
            tokenizer_image_token(
                prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
            )
            .unsqueeze(0)
            .to(self.model.device)
        )
        stop_str = self.conv.sep
        keywords = [stop_str]
        stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)

        with torch.inference_mode():
            output_ids = self.model.generate(
                input_ids,
                images=self.image_tensor,
                do_sample=True if temperature > 0 else False,
                temperature=temperature,
                max_new_tokens=max_new_tokens,
                use_cache=True,
                stopping_criteria=[stopping_criteria],
            )

        input_token_len = input_ids.shape[1]
        outputs = self.tokenizer.batch_decode(
            output_ids[:, input_token_len:], skip_special_tokens=True
        )[0]
        outputs = outputs.strip()
        if outputs.endswith(stop_str):
            outputs = outputs[: -len(stop_str)]
        outputs = outputs.strip()

        print(outputs)

        self.conv.messages[-1][-1] = outputs
        self.history = prompt
        # if args.debug:
        #     print("\n", {"prompt": prompt, "outputs": outputs}, "\n")
        return outputs,self.history 


if __name__ == "__main__":
    yi = YiVL()
    image_path, query = "VL/images/cats.jpg","given the image , answer the question bellow: \nhow many cats are in the image?"
    yi.new_chat(image_path, query)

**Comment by markli404** [comment]
> ```
> import torch
> import traceback
> import os
> 
> import argparse
> import sys
> 
> # 获取当前文件的绝对路径
> current_file_path = os.path.abspath(__file__)
> # 获取当前文件所在的文件夹路径
> current_file_dir = os.path.dirname(current_file_path)
> 
> sys.path.append(current_file_dir+"/../")
> 
> import torch
> from llava.conversation import conv_templates
> from llava.mm_utils import (
>     KeywordsStoppingCriteria,
>     expand2square,
>     get_model_name_from_path,
>     load_pretrained_model,
>     process_images,
>     tokenizer_image_token,
> )
> 
> from llava.model.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, key_info
> from PIL import Image
> 
> 
> model_id = 'yi/Yi-VL-6B'
> revision = 'v1.0.0'
> 
> def disable_torch_init():
>     """
>     Disable the redundant torch default initialization to accelerate model creation.
>     """
>     import torch
> 
>     setattr(torch.nn.Linear, "reset_parameters", lambda self: None)
>     setattr(torch.nn.LayerNorm, "reset_parameters", lambda self: None)
> 
> def load_image(image_file):
>     image = Image.open(image_file).convert("RGB")
>     return image
> 
> class YiVL:
> 
>     def __init__(self,model_path="models/Yi-VL-6B/",load_8bit=False, load_4bit=False):
> 
>         disable_torch_init()
>         key_info["model_path"] = model_path
>         get_model_name_from_path(model_path)
>         self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(model_path=model_path,load_8bit=False, load_4bit=False)
>         
>         self.conv = conv_templates["mm_default"].copy()
>         self.roles = self.conv.roles
>         self.history = None
>         
> 
>     def clear(self):
>         self.history = None
>         self.conv = conv_templates["mm_default"].copy()
>         self.image_tensor = None
> 
> 
>     def chat(self,query,temperature=0.8,max_new_tokens=1024):
>         self.conv.append_message(self.conv.roles[0], query)
>         self.conv.append_message(self.conv.roles[1], None)
>         prompt = self.conv.get_prompt()
> 
>         input_ids = (
>             tokenizer_image_token(
>                 prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
>             )
>             .unsqueeze(0)
>             .to(self.model.device)
>         )
>         stop_str = self.conv.sep
>         keywords = [stop_str]
>         stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)
> 
>         with torch.inference_mode():
>             output_ids = self.model.generate(
>                 input_ids,
>                 images=self.image_tensor,
>                 do_sample=True if temperature > 0 else False,
>                 temperature=temperature,
>                 max_new_tokens=max_new_tokens,
>                 use_cache=True,
>                 stopping_criteria=[stopping_criteria],
>             )
> 
>         input_token_len = input_ids.shape[1]
>         outputs = self.tokenizer.batch_decode(
>             output_ids[:, input_token_len:], skip_special_tokens=True
>         )[0]
>         outputs = outputs.strip()
>         if outputs.endswith(stop_str):
>             outputs = outputs[: -len(stop_str)]
>         outputs = outputs.strip()
> 
>         print(outputs)
> 
>         self.conv.messages[-1][-1] = outputs
>         self.history = prompt
>         return outputs,self.history
>     
>     
>     def new_chat(self,image_path, query,temperature=0.8,max_new_tokens=1024):
>         self.clear()
>         
>         # load image
>         image = load_image(image_path)
>         self.image_tensor = process_images([image], self.image_processor, self.model.config)
>         self.image_tensor = self.image_tensor.to(self.model.device, dtype=torch.bfloat16)
> 
>         query = DEFAULT_IMAGE_TOKEN + "\n" + query
>         self.conv.append_message(self.conv.roles[0], query)
>         self.conv.append_message(self.conv.roles[1], None)
>         prompt = self.conv.get_prompt()
> 
>         input_ids = (
>             tokenizer_image_token(
>                 prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
>             )
>             .unsqueeze(0)
>             .to(self.model.device)
>         )
>         stop_str = self.conv.sep
>         keywords = [stop_str]
>         stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)
> 
>         with torch.inference_mode():
>             output_ids = self.model.generate(
>                 input_ids,
>                 images=self.image_tensor,
>                 do_sample=True if temperature > 0 else False,
>                 temperature=temperature,
>                 max_new_tokens=max_new_tokens,
>                 use_cache=True,
>                 stopping_criteria=[stopping_criteria],
>             )
> 
>         input_token_len = input_ids.shape[1]
>         outputs = self.tokenizer.batch_decode(
>             output_ids[:, input_token_len:], skip_special_tokens=True
>         )[0]
>         outputs = outputs.strip()
>         if outputs.endswith(stop_str):
>             outputs = outputs[: -len(stop_str)]
>         outputs = outputs.strip()
> 
>         print(outputs)
> 
>         self.conv.messages[-1][-1] = outputs
>         self.history = prompt
>         # if args.debug:
>         #     print("\n", {"prompt": prompt, "outputs": outputs}, "\n")
>         return outputs,self.history 
> 
> 
> if __name__ == "__main__":
>     yi = YiVL()
>     image_path, query = "VL/images/cats.jpg","given the image , answer the question bellow: \nhow many cats are in the image?"
>     yi.new_chat(image_path, query)
>    
>         
> ```

确实会有这种问题，暂时不太清楚什么原因导致的，我这边用中文prompt就可以避免。

**Comment by Sanster** [comment]
应该是训练集数据清理没做好，TextVQA 的数据中 answers 会有这类数据

<img width="924" alt="image" src="https://github.com/01-ai/Yi/assets/3998421/74c817d2-71b9-4290-951c-929856a11489">
