### ISSUE TITLE
Yi-VL 支持最新版的transformers

### ISSUE THREAD

**Issue by luohao123** [01-ai/Yi#386]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

最新版的LLava 键值冲突了。

是否能支持一下最新版本的transofmers？ 也许代码会更简洁？

### Solution

是否能支持一下最新版本的transofmers？ 也许代码会更简洁？

### Alternatives

是否能支持一下最新版本的transofmers？ 也许代码会更简洁？

### Anything Else?

是否能支持一下最新版本的transofmers？ 也许代码会更简洁？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
可以提供一下报错信息吗？

**Comment by luohao123** [comment]
@Yimi81  

```
transformers/models/auto/configuration_auto.py", line 828, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
```

稍微新一点的transoformers都会冲突，因为transformers已经内置了llava架构了。

**Comment by Yimi81** [comment]
我需要更多的信息才能复现，你运行的是哪个脚本，报错堆栈能否全部提供？

**Comment by luohao123** [comment]
3.37

我pull了一下嘴心的代码，你那边能浮现吗

**Comment by Yimi81** [comment]
我这边是最新的transformer:4.37.2, 运行的是singleinference脚本，一切正常。我认为是你的虚拟环境有问题，你是不是之前配置过llava项目。你可以新开一个虚拟环境，按照我们的requirement.txt配置环境，这是正常的。

**Comment by luohao123** [comment]
我试一下。

另外，想请问一下yivl的pretrain阶段的数据有开源吗

**Comment by Yimi81** [comment]
预训练阶段的数据采用的是Laion-400M， 可以看一下readme
