### ISSUE TITLE
md5&sha256 code is incorrect

### ISSUE THREAD

**Issue by Jack-devnlp** [01-ai/Yi#403]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
- PyTorch:2.0.1+cu118
- CUDA:11.8
```

### Current Behavior

the md5&sha256 code of transfoemers package is incorrect in "conda-lock.yml"
<img width="767" alt="Snipaste_2024-02-18_23-28-42" src="https://github.com/01-ai/Yi/assets/72558668/9a305b71-7c8c-4222-acd8-d9fba1828f42">

### Expected Behavior

md5: 8e1add862a24a58cfdfd710805eb884b
sha256: 1ff6b32750a2c6fc1823ea3f440939de05e05c44114f5709d2120007b00a4ec5

### Steps to Reproduce

I find this error when build docker image from Dockerfile

**Comment by markli404** [comment]
> build docker image from Dockerfile

would you please provide your sample code to reproduce this error? Thanks!

**Comment by markli404** [comment]
> docker build .

Thank you for noticing us! I just checked you are correct.
