### ISSUE TITLE
VL模型没有对图像中的中文理解能力

### ISSUE THREAD

**Issue by xpcc355** [01-ai/Yi#418]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

VL模型没有对图像中的中文理解能力，但是能够理解英文和数字。后续会对模型进行调整吗？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by markli404** [comment]
根据 #381 以及下面的[回复](https://github.com/01-ai/Yi/issues/381#issuecomment-1925608548)。Yi-VL暂时没有对光学字符识别(OCR)的能力进行增强。后续可能会对模型进行调整，如果有更准确的信息，我会在这里同步。

**Comment by xpcc355** [comment]
好的 谢谢！
