### ISSUE TITLE
Hallucination after finetuning

### ISSUE THREAD

**Issue by YingchaoX** [01-ai/Yi#42]
After lora sft `Yi-34B` with `sharegpt` and `oaast_sft` datasets, the self cognition like this
<img width="1436" alt="Screenshot 2023-11-07 at 12 05 31" src="https://github.com/01-ai/Yi/assets/3861285/85bc01aa-f9ea-4a0d-8f0f-a1092f1221d9">

Back to the base model, try to use `generate()` to answer the self cognition question...
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("/models/Yi-34B", device_map="auto", torch_dtype="auto", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("/models/Yi-34B", trust_remote_code=True)
inputs = tokenizer("我是一个AI助手，可以回答您的问题并提供信息。我由", return_tensors="pt")
outputs = model.generate(inputs.input_ids.cuda(), max_new_tokens=128)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```
the output like this 
```
我是一个AI助手，可以回答您的问题并提供信息。我由OpenAI开发，旨在提供准确、无偏见的信息。如果您有任何问题，请随时提问。
```

**Comment by nickeyfff** [comment]
laugh~

**Comment by itsliupeng** [comment]
I think it's a problem with the data in sharegpt.

**Comment by YingchaoX** [comment]
> I think it's a problem with the data in sharegpt.

[sharegpt](https://huggingface.co/datasets/kimnt93/zh-sharegpt ) this dataset does not mention content related to self-awareness or openai. 🤣

**Comment by ZhaoFancy** [comment]
Could you provide detailed steps on how you finetune the model and also the dataset you use?

Our developers will look into it with you together.

**Comment by YingchaoX** [comment]
> Could you provide detailed steps on how you finetune the model and also the dataset you use?
> 
> Our developers will look into it with you together.

Of course. You could try the base model first, that is easy to reproduce. See the code below.

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
model_id = "01-ai/Yi-34B"
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype="auto", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
inputs = tokenizer("我是一个AI助手，可以回答您的问题并提供信息。我由", return_tensors="pt")
outputs = model.generate(inputs.input_ids.cuda(), max_new_tokens=128)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# 我是一个AI助手，可以回答您的问题并提供信息。我由OpenAI开发，旨在提供准确、无偏见的信息。如果您有任何问题或需要帮助，请随时提问。
```
##

For SFT, I used this [LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory) project and the major parameter is below.
```json
{
    "stage": "sft",
    "model_name_or_path": "01-ai/Yi-34B",
    "do_train": true,
    "finetuning_type": "lora",
    "template": "default",
    "dataset": "oaast_sft_zh,sharegpt_zh,self_cognition", 
    "cutoff_len": 512,
    "learning_rate": 1e-5,
    "num_train_epochs": 10,
    "bf16": true,
    "per_device_train_batch_size": 8,
    "gradient_accumulation_steps": 1,
    "lr_scheduler_type": "cosine",
    "report_to": "all",
    "warmup_ratio": 0.1,
    "weight_decay": 0.1,
    "max_grad_norm": 1.0,
    "lora_rank": 16,
    "lora_dropout": 0.1,
    "lora_target": "k_proj,o_proj,q_proj,v_proj"
}
```
- the `<NAME>` and `<AUTHOR>` in `self_cognition.json` have been changed to the real company name instead of default value or `Openai`.
- the template just default.

Then the train command.
```bash
torchrun --nproc-per-node 8 src/train_bash.py json_config_above.json
```

Thx.

**Comment by Joran1101** [comment]
Interesting~

**Comment by WooyoohL** [comment]
![{406700BA-49D8-407f-ACB6-B2E9FDE47FB7}](https://github.com/01-ai/Yi/assets/101500442/e4844ba7-c82c-4a51-9cc1-6f138bcc7165)
I also have this question. After loaded the Yi-6b model, I did nothing else but ask who are you, its answer is "an ai assistant developed by OpenAI."

**Comment by Rorschaaaach** [comment]
> > I think it's a problem with the data in sharegpt.
> 
> [sharegpt](https://huggingface.co/datasets/kimnt93/zh-sharegpt) this dataset does not mention content related to self-awareness or openai. 🤣

盲猜应该是本身训练的base模型里用到了openai的数据，改名改的不纯粹微调后就显现出来了，改名相当于加了一层封印，微调之后封印松动了

**Comment by itsliupeng** [comment]
检索我们用到的 网页 数据中，确实有跟 OpenAI ChatGpt 相关的内容，导致 pretrain base model 记住了这种自我介绍形式

> ChatGPT是由OpenAI开发的。OpenAI是一个非营利组织，于2015年由伊隆·马斯克（Elon Musk）、萨姆·奥尔特曼（Sam Altman）等人创立。
OpenAI致力于进行与人工智能（AI）相关的研究和开发，并旨在构建先进的人工智能模型，解决与推动和利用人工智能相关的问题

> 1.简单介绍下你自己
当然可以。我是一个由OpenAI开发的自然语言处理模型，名为ChatGPT。我基于GPT-3.5模型，是一个大型的语言模型，能够理解并生成人类语言。我可以用于回答各种各样的问题，提供信息和建议，也可以与用户进行聊天互动。我是一个无情感、无偏见和中立的程序，不会对任何问题表达主观意见或价值判断，只会根据我的训练数据和算法尽可能准确地回答您的问题
