### ISSUE TITLE
Yi-VL-34B在推理时支持切分模型吗

### ISSUE THREAD

**Issue by zhaohm14** [01-ai/Yi#421]
请问在推理阶段，可以将Yi-VL-34B切分到多个GPU上吗？

**Comment by Yimi81** [comment]
可以，默认就是切分的，VL-34B我这边测试需要55G，3x3090

**Comment by zhuyr97** [comment]
> 可以，默认就是切分的，VL-34B我这边测试需要55G，3x3090

python cli.py --model-path path-to-yi-vl-model --image path-to-image  

调用时是默认自动切分的嘛

**Comment by Yimi81** [comment]
是的，代码在这里 https://github.com/01-ai/Yi/blob/04867ef887d3cf86b6ff64fd08f942977a25365d/VL/llava/mm_utils.py#L75

**Comment by zhaohm14** [comment]
明白了，多谢！
