### ISSUE TITLE
Will opensource llava trainer?

### ISSUE THREAD

**Issue by lucasjinreal** [01-ai/Yi#428]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

Will opensource llava trainer?

### Solution

Will opensource llava trainer?

### Alternatives

Will opensource llava trainer?

### Anything Else?

Will opensource llava trainer?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
no, if you want finetune vl model, please refer to #348

**Comment by lucasjinreal** [comment]
EXCELLENT.
