### ISSUE TITLE
词表大小和embedding层大小不匹配？

### ISSUE THREAD

**Issue by Mr-KenLee** [01-ai/Yi#448]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS: Ubuntu 18.04.6 LTS
- Python:3.10.13
- PyTorch:2.2.1+cu121 (True)
- CUDA:cu121
```

### Current Behavior

我当前是在两张3090上用LoRA指令微调Yi-Chat-6B，我遇到了RuntimeError: CUDA error: device-side assert triggered错误。通过设置CUDA_LAUNCH_BLOCKING=1，我找到问题所在是embedding层部分。
在我的任务中，我采用了eos token，即<|endoftext|>，其对应id为64001，但是实际上，模型文件仅设置了词表大小为64000。
请问这个问题如何解决？我尝试过更改config，但是因为模型中参数矩阵形状不匹配仍然报错。我是应该修改eos token来解决问题吗？

### Steps to Reproduce

如Current Behavior所述

**Comment by Yimi81** [comment]
Yi-6B-Chat的eso token是<|im_end|>, 采用的是chatml格式。

**Comment by Yimi81** [comment]
加载tokenizer的时候设置use_fast=False
