### ISSUE TITLE
论文中评测ICL能力具体是怎么做的

### ISSUE THREAD

**Issue by cobraheleah** [01-ai/Yi#450]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

麻烦简单讲下论文中评测ICL能力具体是怎么做的吗，没太看明白，可以给个具体示例

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by cobraheleah** [comment]
@Yimi81 可以帮忙解答下吗

**Comment by Yimi81** [comment]
您好，具体的细节我也不清楚，需要咨询预训练部门的同事，但是有关paper中ICL这一段的内容描述的还是比较清楚的，我的理解如下图：
![image](https://github.com/01-ai/Yi/assets/66633207/9de1c5c9-928c-4ed9-8847-6195e108f9a4)
结论就是Yi-34B 在ICL上的性能是不错的，而且如果进一步scale up模型规模可以让其通过ICL来推断更复杂的函数。可能我的理解也有错误，如果您还有问题可以进一步提出我可以去帮您咨询一下。

**Comment by cobraheleah** [comment]
好的，我大概了解了，非常感谢，请问评测数据可以开源吗

**Comment by Yimi81** [comment]
抱歉，目前不会
