### ISSUE TITLE
Unexpected output when playing with Yi-34B on huggingface chat

### ISSUE THREAD

**Issue by jiangzizi** [01-ai/Yi#458]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
https://huggingface.co/spaces/01-ai/Yi-34B-Chat
```

### Current Behavior

Prompt "Beijing -> China, Berlin -> Germany, Paris -> France, Taipei" leads to "Taipei -> Taiwan"

### Steps to Reproduce

Just follow my prompt.

**Comment by Yimi81** [comment]
Thanks for your input. We are closely examining the case per our safety guidelines.

**Comment by xiaoToby** [comment]
@jiangzizi wo juede ni zai gao shi qing
