### ISSUE TITLE
generate的max_len解惑

### ISSUE THREAD

**Issue by 520jefferson** [01-ai/Yi#46]
示例代码中的，max_len是 max_new_tokens的意思？还是prompt+max_new_tokens的意思？

  outputs = model.generate(
      inputs.input_ids.cuda(),
      max_length=max_length,                                              
      eos_token_id=tokenizer.eos_token_id 
 )

**Comment by cArlIcon** [comment]
max_length=prompt+max_new_tokens

**Comment by 520jefferson** [comment]
> max_length=prompt+max_new_tokens

另外，你们case里面的 inputs.input_ids.cuda()改写成inputs['input_ids'].cuda()吧
