### ISSUE TITLE
想請問Yi-34B-Chat-4bits串接langchain的create_pandas_dataframe_agent function無法達到預期的效果

### ISSUE THREAD

**Issue by minikai** [01-ai/Yi#470]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
略
```

### Current Behavior

串接langchain的create_pandas_dataframe_agent function在問問題時，不會針對給的dataframe做運算回出運算結果，而是會一段應該是正確的程式碼，不會回給正確的運算結果。

### Expected Behavior

如果使用的是openai的相關llm串接langchain的create_pandas_dataframe_agent function在問問題時，會針對給的dataframe做運算回出運算結果。

### Steps to Reproduce

略

**Comment by Yimi81** [comment]
yi api目前还不支持function call, 用于agent效果可能不太好

**Comment by jialinhappy** [comment]
那如果基于ms-agent数据集对yi-34B-chat进行微调,能实现function call的功能吗

**Comment by Yimi81** [comment]
@jialinhappy 能，微调后就有function call能力了，具体效果需要自己测试，除了ms-agent还有这个也可以https://mp.weixin.qq.com/s/I-EL3qlXVHCp1jNRDihEhw，不管是ms-agent还是这个，微调后都需要使用它们对应实现的server启动后然后调api才行
