### ISSUE TITLE
三阶段数据介绍

### ISSUE THREAD

**Issue by lyc728** [01-ai/Yi#471]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

<img width="513" alt="企业微信截图_17111000685860" src="https://github.com/01-ai/Yi/assets/88084847/84d56010-e09f-4232-b7fb-7c61ba6a9c4f">
你好 有关于这个三阶段数据更为详细的介绍吗？只用图文对100w就可以吗？还有了哪些闭源的数据呢？纯文本的数据是否使用呢？

### Solution

没有看到关于更为详细的三阶段数据介绍

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nuoma** [comment]
你好，是的，100w的图文pair，并没有和列举出来的显著不同的闭源数据，也并没有使用纯文本的数据。
