### ISSUE TITLE
Title  Yi-6B-200K can't be used

### ISSUE THREAD

**Issue by EasonFeng5870** [01-ai/Yi#474]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS: 
- Python:
- PyTorch:
- CUDA:

we are setting up a Yi-6B-200K model, it can't answer any questions, even common 1+1=

This is a bad model. 

Am I wrong? btw, this model doesn't have a useful chat template in tokenizer_config.json, so we try a lot of time to find the use of this model:

### user: 1+1= \n ### assistant:
```

### Current Behavior

which is cant used for any questions.

### Steps to Reproduce

just query

### Anything Else?

none

**Comment by Yimi81** [comment]
The 9B we provided is a base model, not a chat model, so there is no chat template available. It cannot be used for chat, it only works after fine-tuning
In addition, if there is a problem of continuous repetition when using 9B, you can refer to the `text_generation.py ` in the demo folder to give some `repetition penalties` and other parameters during generation.
