### ISSUE TITLE
how to sft support larger context length?

### ISSUE THREAD

**Issue by lucasjinreal** [01-ai/Yi#48]
if set max_sequence_len to 4k, does the model able to do extrapolation automatically?

**Comment by jiangchengSilent** [comment]
change max_seq_len in script args, as well as max_position_embeddings in config.json in model file to larger value. But this needs more GPU memory. Consider to adjust related hyper-params such as batch_size

**Comment by lucasjinreal** [comment]
I mean, doesit has dynamic ntk or rope scaling inside code.....

**Comment by cArlIcon** [comment]
> I mean, doesit has dynamic ntk or rope scaling inside code.....

No. Just modify max_position_embeddings in config.json. It can extend  context length to 32K for Yi-34 and Yi-6.

**Comment by lucasjinreal** [comment]
Doesn't it will consume too much mem?

**Comment by jiangchengSilent** [comment]
> Doesn't it will consume too much mem?

Yes it is. It takes a lot GPU mem or CPU mem if zero-offload is enabled. So a single node with 8 cards and 900GB CPU mem is not enough for such setting. Please try multi-node training
