### ISSUE TITLE
偶发性的会报错 

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [01-ai/Yi#482]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS: ubuntu20.04
- Python:3.10.12
- PyTorch:2.1.0
- CUDA:12.4. 
- torch.version.cuda '12.1'
```

### Current Behavior

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument tensors in method wrapper_CUDA_cat)

### Steps to Reproduce

Yi-VL-34B/VL/llava/model/llava_arch.py
```
def encode_images(self, images):
        image_features = self.get_model().get_vision_tower()(images)
        image_features (CUDA:3) = self.get_model().mm_projector(image_features (CUDA:0)) 
        return image_features
```

**Comment by ykk624** [comment]
I have a similiar problem. The same error occured on Card 1~7, but card0 is normal. 
I find "weight" appears on different cards(0~7), but "input" still appears on card0, leading mistake below.
Can you give me some device? Thank you!
我有一个相似的问题，卡1~7都报错相同，卡0没报错。我发现weight分布在8张卡上，但是input都分布在卡0上，导致了以下错误。
您能提供下建议吗？感谢。

File "/opt/conda/envs/yi/lib/python3.10/site-packages/torch/nn/functional.py", line 2217, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
