### ISSUE TITLE
Features : openai_api.py support multi turn dialogs.

### ISSUE THREAD

**Issue by DataLearnerAI** [01-ai/Yi#486]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

Although there is a script called [openai_api.py](https://github.com/01-ai/Yi/blob/main/VL/openai_api.py) in VL that can be used to deploy the yi-vl model as openai api style. It seems that this script only process the first msg forever, ignoring the following dialogs

![image](https://github.com/01-ai/Yi/assets/132440409/83408713-1387-43a2-8015-f6ec8a93960f)

Also, if the first msg from user does not contain any images, the server will throws 500 internal error.
![image](https://github.com/01-ai/Yi/assets/132440409/56cf46bc-c08f-4893-8405-03c9d8c59127)

### Solution

I am not sure if this a bug in the script. I have checked the source code, but the code was too long.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
@DataLearnerAI Please update the latest code. I have fixed this issue. In addition, [LMDeploy](https://github.com/InternLM/lmdeploy) supports openai-style server deployment for the Yi VL model. https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving/api_server_vl.md
