### ISSUE TITLE
A large amount of irrelevant information is generated

### ISSUE THREAD

**Issue by kennethxian** [01-ai/Yi#49]
Why did I only ask what 1+1 equals, and it added a bunch of irrelevant information in addition to answering that it equals 2?

**Comment by ZhaoFancy** [comment]
Well, the main reason is that, the first public releases are just **base** models. You can try to finetune on public datasets manually. Or you can wait for our upcoming **chat** version models.

**Comment by kennethxian** [comment]
Thank you
