### ISSUE TITLE
Yi-VL-34b支持int4量化吗？怎么操作

### ISSUE THREAD

**Issue by changqinyao** [01-ai/Yi#492]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

Yi-VL-34b支持int4量化吗？怎么操作

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
应该可以，我没有测试过，请参考这个https://github.com/AutoGPTQ/AutoGPTQ/issues/304，只量化LLM，忽略视觉编码器

**Comment by liufangtao** [comment]
我设置load_4bit=True,发现没有什么用
