### ISSUE TITLE
LLama3发表了，啥时候Yi出新版本啊

### ISSUE THREAD

**Issue by WSC741606** [01-ai/Yi#500]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

https://github.com/meta-llama/llama3​
https://ai.meta.com/blog/meta-llama-3/

### Solution

希望尽快出超越Llama3的版本~
yi-6B-chat的64k词表和4k上下文好像有点滞后了

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nuoma** [comment]
新模型在路上了～

**Comment by win10ogod** [comment]
倒閉了?
