### ISSUE TITLE
where can I find the training  code or script for YI-VL

### ISSUE THREAD

**Issue by verigle** [01-ai/Yi#505]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

I want to fine-tune the model of Yi-VL, but I could not find the training code or script

### Solution

can I use the training code of llava ?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nuoma** [comment]
Hi, we are not providing training code for VL. Yes, you can try to use llava or SWIFT framework for VL finetunes.
