### ISSUE TITLE
这玩意怎么打的广告？有商机

### ISSUE THREAD

**Issue by Le8r0nJames** [01-ai/Yi#53]
![image](https://github.com/01-ai/Yi/assets/90502403/74c458a8-7ffa-4662-a00c-1edfc3914090)

**Comment by ZhaoFancy** [comment]
Thanks for reporting.

Could you provide which model did you use? And also the prompt?

---

@renxiaoyi Could you check it in our training dataset?

**Comment by Le8r0nJames** [comment]
Hi, 我用的是4bit的GPTQ model “TheBloke/Yi-34B-GPTQ”，prompt就是“我怎样才能吃的更健康？”

**Comment by yang1111-gif** [comment]
人家应该是base模型，不是chat模型。但是我感觉yi的官方反应速度太慢了。

**Comment by ZhaoFancy** [comment]
> 但是我感觉yi的官方反应速度太慢了。

🏃‍♂️🏃‍♂️🏃‍♂️

**Comment by yeyupiaoling** [comment]
后面会开源Chat模型吗？

**Comment by ZhaoFancy** [comment]
> 后面会开源Chat模型吗？

是的

**Comment by yeyupiaoling** [comment]
好的

**Comment by renxiaoyi** [comment]
> Thanks for reporting.
> 
> Could you provide which model you use? And also the prompt?
> 
> @renxiaoyi Could you check it in our training dataset?

Indeed there are quite some ads content for the brand "Fitbit" in our training dataset. We may consider stricter ads reducing strategies if needed.

**Comment by AmeowCAT** [comment]
> Hi, 我用的是4bit的GPTQ model “TheBloke/Yi-34B-GPTQ”，prompt就是“我怎样才能吃的更健康？”

能问下你使用量化后的模型占用了多少显存吗

**Comment by ZhaoFancy** [comment]
再试试 Chat 模型？🤗
