### ISSUE TITLE
请问有Yi-VL可以实现few-shot（in-context）数据的推理或微调吗？

### ISSUE THREAD

**Issue by waltonfuture** [01-ai/Yi#538]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Motivation

希望用Yi-VL实现多模态few-shot的训练或推理

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yimi81** [comment]
目前不支持多图输入，多模态few-shot的推理应该是不可以
