### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by 2922832737C** [01-ai/Yi#54]
exllama这个包怎么安装不上

**Comment by ZhaoFancy** [comment]
FYI: https://github.com/01-ai/Yi/issues/21

**Comment by 2922832737C** [comment]
这个还不是很懂，能解释的清楚一些吗

**Comment by ZhaoFancy** [comment]
抱歉，我是指，这个包目前不用安装。

**Comment by 2922832737C** [comment]
我还是想问一下，我requirements.txt中的下载完了之后，我该继续执行什么命令来运行他
