### ISSUE TITLE
Yi-6B-200k推理时一定要安装flash attention库吗？

### ISSUE THREAD

**Issue by alllzh** [01-ai/Yi#56]
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

**Comment by GXKIM** [comment]
> ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

需要

**Comment by loofahcus** [comment]
> ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

Yes. When the seq_length is big, If you don't use memory-efficient attention technique, the attention_mask (size of seq_length * seq_length) will consume too much memory
