### ISSUE TITLE
200k上下文

### ISSUE THREAD

**Issue by FrankWhh** [01-ai/Yi#59]
请问推理200k上下文需要多大的资源？看模型文件，没看到常规的提升长度手段

**Comment by excellent-ai** [comment]
Duplicate of #55

**Comment by FrankWhh** [comment]
这不是同一个问题

**Comment by learninmou** [comment]
demo中给出了一个text_generation_tp.py样例，如果是输入长度200K，在不开启offload技术且不量化的情况下，34B模型推理需要400GB以上的显存，我们测试使用是8卡A100/A800。

**Comment by FrankWhh** [comment]
硬算啊！显存占用400G，那速度呢？

**Comment by yuyi1111** [comment]
6B模型输入长度200K需要大概多少显存呢？

**Comment by wangye01inf** [comment]
@yuyi1111 2TP 情况下 BS=1 每张卡大约需要 60-80GB 左右显存

**Comment by yuyi1111** [comment]
> @yuyi1111 2TP 情况下 BS=1 每张卡大约需要 60-80GB 左右显存

能麻烦请教一下200K推理的情况吗？我用的text_generation_tp.py进行推理，两张80G显存的a800还是报cuda oom

**Comment by wangye01inf** [comment]
@yuyi1111 请问有安装 flash attention 吗？这个对显存影响挺大的

**Comment by yuyi1111** [comment]
> flash attention

谢谢！安装了之后就能跑起来了

**Comment by happy15** [comment]
> 6B模型输入长度200K需要大概多少显存呢？

同问，mbp 14 with 16g上通过ollama跑没跑起来。

**Comment by learninmou** [comment]
> > 6B模型输入长度200K需要大概多少显存呢？
> 
> 同问，mbp 14 with 16g上通过ollama跑没跑起来。

你好，没有在mbp上测试过，理论上需要NVIDIA的GPU。

**Comment by jaywongs** [comment]
> @yuyi1111 请问有安装 flash attention 吗？这个对显存影响挺大的

仅仅只是安装flash_attn吗？ 代码text_generation_tp.py里并没有任何使用到flash_attn呀

**Comment by jaywongs** [comment]
> > flash attention
> 
> 谢谢！安装了之后就能跑起来了

请问能详细了解一下步骤吗？因为我这边安装了也还是gpu oom

**Comment by yuyi1111** [comment]
@jaywongs 我之前安装了flash attention之后就可以跑起来了，也许是你的显存不够？

**Comment by mary-0830** [comment]
> > > flash attention
> > 
> > 
> > 谢谢！安装了之后就能跑起来了
> 
> 请问能详细了解一下步骤吗？因为我这边安装了也还是gpu oom

同问，用6张80G的卡还是会报oom的错。计算仅在一张卡上，所以导致了这个问题，请问怎么解决的呢？
