### ISSUE TITLE
Generates other languages in an incorrect encoding 

### ISSUE THREAD

**Issue by samuelazran** [01-ai/Yi#64]
For example, I prompt it to extract an entity from a text in Hebrew, and it produces: "���� ���"
It seems to work ok with language understanding of Hebrew but the decoding of the tokens when generating Hebrew seems buggy. Could it be the tokenizer? what could be the issue?

I'm using exllamav2 with the model LoneStriker/Yi-34B-200K-6.0bpw-h6-exl2 from Huggingface datasets.

BTW, thanks for opening this model, and I wish you success in your endeavors, around 30B parameters and 3T pretraining tokens seem to be closer to the optimal spot then existing models.

Looking forward to the "instruct" or "chat" version.

**Comment by ZhaoFancy** [comment]
Could you share your prompt to us?

Also note that https://github.com/01-ai/Yi/issues/25#issuecomment-1797386811

> we explicitly filtered other languages in the training dataset

**Comment by samuelazran** [comment]
> Could you share your prompt to us?
> 
> Also note that [#25 (comment)](https://github.com/01-ai/Yi/issues/25#issuecomment-1797386811)
> 
> > we explicitly filtered other languages in the training dataset
Thank you for your response.

I've tested it now with Huggingface and it works fine. 
Before that I've tested it with Exllamav2 and the issue occurred. I now suspect the issue is in the way Exllamav2 utilizes your custom tokenizer. I will refer the issue to them.

Thanks
