### ISSUE TITLE
能否提供一个在线体验的网站。

### ISSUE THREAD

**Issue by Rodert** [01-ai/Yi#65]

**Comment by ZhaoFancy** [comment]
抱歉，目前 Base Model 暂无提供计划。
接下来 Chat 版模型发布后，我们会重新考虑。

Ref: https://huggingface.co/01-ai/Yi-34B/discussions/10

**Comment by shengkaixuan** [comment]
chat 模型预计什么时候发布？

**Comment by lphkxd** [comment]
同问

**Comment by franva** [comment]
I'd also be curious about the release date for the chat version model. 

thanks
