### ISSUE TITLE
使用自己的数据进行sft的时候，初始loss特别高，这个现象合理吗

### ISSUE THREAD

**Issue by yoosan** [01-ai/Yi#68]
用的是llama-factory这个框架做sft，相同的数据，baichuan2的模型loss大概从2左右下降，yi-34b初始loss能到5.2，有没有遇到一样情况的

**Comment by chenyzh28** [comment]
我的从10左右开始下降，跑了10几个step后到零点几了，都怀疑是不是过拟合了。

**Comment by Hades-Z** [comment]
> 我的从10左右开始下降，跑了10几个step后到零点几了，都怀疑是不是过拟合了。

评估结果是不是过拟合了呀？

**Comment by chenyzh28** [comment]
> > 我的从10左右开始下降，跑了10几个step后到零点几了，都怀疑是不是过拟合了。
> 
> 评估结果是不是过拟合了呀？

看结果好像比较正常，没有过拟合

**Comment by ZhaoFancy** [comment]
正常的，不同模型之间的 loss 不具有可对比性。
