### ISSUE TITLE
如何用oobabooga / text-generation-webui来加载Yi模型呢？

### ISSUE THREAD

**Issue by quartets** [01-ai/Yi#72]
我试了很多参数组合都加载不成功。

**Comment by JamesFlare1212** [comment]
有一个 GGUF 格式的可以用 https://huggingface.co/TheBloke/Yi-34B-GGUF/tree/main

**Comment by krisshen2021** [comment]
theBloke 出了GPTQ的，在text-gen里用transformer的model loader, 启动text-gen时，要加--trust-remote-code的flag, 然后在transformer的loading参数里勾选disable_exllama.
