### ISSUE TITLE
Asking for the benchmark testing code

### ISSUE THREAD

**Issue by ShiLuohe** [01-ai/Yi#79]
I've tested both 6B and 34B model on MMLU, the outcome isn't that good and shows a wired pattern. Would you upload the code used for testing benchmarks for the scores in README.md ?

**Comment by cArlIcon** [comment]
Our test result are same as huggingface leaderboard. You can find reference here:https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard -> "About" -> "How it works"
