### ISSUE TITLE
如何通过docker部署？docker镜像在哪里？

### ISSUE THREAD

**Issue by njflove** [01-ai/Yi#81]

**Comment by tianyu150** [comment]
同问，1.1的docker镜像是做什么的？ 开发环境？这个镜像的用法？

**Comment by ZhaoFancy** [comment]
> 1.1的docker镜像是做什么的？ 开发环境？这个镜像的用法？

这个镜像是方便大家运行本仓库内的实例代码的。

和运行其它 GPU 的镜像一样，可以通过 `docker run --rm --gpus all IMAGE_ADDRESS` 来运行。当然，如果你是在云上运行的话，请参考各个云厂商的文档。
