### ISSUE TITLE
多卡部署参数设置

### ISSUE THREAD

**Issue by BearsEatLardCake** [01-ai/Yi#82]
Traceback (most recent call last):
  File "autodl-tmp/Yi/demo/text_generation_tp.py", line 111, in <module>
    main(args)
  File "autodl-tmp/Yi/demo/text_generation_tp.py", line 76, in main
    torch.cuda.set_device(int(os.environ["LOCAL_RANK"]))
  File "/root/miniconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'
我有三张卡，该怎么修改text_generation_tp.py的参数才能正确运行

**Comment by wrennywang** [comment]
CUDA_VISIBLE_DEVICES=0,1 torchrun ...

**Comment by heloproc** [comment]
﻿ To run text_generation_tp.py on three GPUs, you need to modify the following parameters:

* **WORLD_SIZE** should be set to 3.
* **LOCAL_RANK** should be set to 0, 1, or 2, depending on which GPU you are using.
* **CUDA_VISIBLE_DEVICES** should be set to the comma-separated list of GPU IDs that you are using. For example, if you are using GPUs 0, 1, and 2, you would set CUDA_VISIBLE_DEVICES to "0,1,2".

Once you have modified these parameters, you can run text_generation_tp.py as follows:

```
python text_generation_tp.py --world_size 3 --local_rank 0 --cuda_visible_devices 0,1,2
```

This will start the text generation task on three GPUs
