### ISSUE TITLE
Python packaging and dependency management suggestion

### ISSUE THREAD

**Issue by shenxiangzhuang** [01-ai/Yi#87]
Use [requirements.txt](https://github.com/01-ai/Yi/blob/main/requirements.txt) is ok, but it may owe some technical debt. It's a better choice to use [Poetry](https://python-poetry.org/) or [Rye](https://rye-up.com/) to do the packaging and dependency management.

**Comment by ZhaoFancy** [comment]
We understand that and may replace it with [conda lock file](https://github.com/conda/conda-lock) in the public release soon.

As for Poetry, it doesn't work well with pytorch *yet* based on our limited experience. See https://github.com/python-poetry/poetry/issues?q=is%3Aissue+is%3Aopen+pytorch

We haven't tried Rye before. Thanks for the link!

**Comment by shenxiangzhuang** [comment]
Yes, I checked and found there do have some problems related to using Torch in Poetry. I didn't have so much experience in this, so I searched some related code & comments, hope which can help in a way:

- https://github.com/python-poetry/poetry/issues/6409
- https://github.com/mitsuhiko/rye/issues/460

- [Usage in langchain: poetry + torch](https://github.com/langchain-ai/langchain/blob/0fc8fd12bd2e8c6a61ad3cbe7e2e64525667af8b/libs/langchain/pyproject.toml#L32)

I'm happy that we already notice the problem in [requirements.txt](https://github.com/01-ai/Yi/blob/main/requirements.txt) and I just give a optional suggestion. Feel free to close this issue.
