### ISSUE TITLE
多轮对话sft

### ISSUE THREAD

**Issue by LiuChen19960902** [01-ai/Yi#88]
请问按照官方给的sft example, 多轮对话应该如何组织呢

**Comment by jiangchengSilent** [comment]
请参考https://huggingface.co/datasets/Dahoas/rm-static?row=0，将多轮Human、Assist的对话拼接入prompt当中

**Comment by LiuChen19960902** [comment]
感谢回复~

**Comment by ZhaoFancy** [comment]
https://github.com/01-ai/Yi/pull/86

这个 merge 之后，可能会有影响。

**Comment by teaguexiao** [comment]
找到多轮对话的格式整理好之后，但是sft脚本执行的时候好像识别不了。要自己做一个raw_datasets.py文件吗？

**Comment by teaguexiao** [comment]
> 按照多轮对话的格式整理好之后，但是sft脚本执行的时候好像识别不了。要自己做一个raw_datasets.py文件吗？

解决了，需要定义一个自己的文件格式在data_utils.py里面
