### ISSUE TITLE
There is no special token like BERT [CLS] token for classification?

### ISSUE THREAD

**Issue by realyinchen** [01-ai/Yi#92]
![token](https://github.com/01-ai/Yi/assets/24246630/1b92644e-7ea8-4cd5-adac-7ae758d311c1)
Here is my code
`
from transformers import AutoTokenizer

model_chpt = "01-ai/Yi-34B"
tokenizer = AutoTokenizer.from_pretrained(model_chpt, trust_remote_code=True)

inputs = tokenizer("做tokenization时没有看到标志首尾的特殊token：CLS和SEP")
print(f"Input ID: {inputs.input_ids}")
tokens = tokenizer.convert_ids_to_tokens(inputs.input_ids)
print(f"Token: {tokens}")
print(f"Sentence: {tokenizer.convert_tokens_to_string(tokens)}")
`

**Comment by loofahcus** [comment]
Yes, we didn't use `CLS` and `SEP` in our base model, you can add them yourself if you want, thx.
