### ISSUE TITLE
花了两天时间安装和测试34B，为啥prompt没用？这个是没法进行对话嘛，是否有chat模型下载？

### ISSUE THREAD

**Issue by wujingbo-web** [01-ai/Yi#95]
(yi34b) [root@localhost Yi-34B]# python Yi/demo/text_generation_fortest.py  --model Yi-34B  --tokenizer Yi-34B   --max-tokens 4096  --eos-token $'\n'  --prompt "请介绍广州一日游行程\n" --streaming 
Namespace(model='Yi-34B', tokenizer='Yi-34B', max_tokens=4096, streaming=True, prompt='请介绍广州一日游行程\\n', eos_token='\n')
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:33<00:00,  4.84s/it]
请介绍广州一日游行程\n。

**Comment by loofahcus** [comment]
这个 case 中，你可以尝试把 `--eos-token $'\n'` 这个配置去掉。
另外，这个是 base 模型，chat 模型将在本月晚些时候发布，请耐心等待，感谢您的关注～

**Comment by renoyuan** [comment]
插个眼，等一个chat 版本。
