### ISSUE TITLE
你好，什么时候考虑发布更小的模型，适合移动端的？

### ISSUE THREAD

**Issue by LMR2018** [01-ai/Yi#97]
你好，什么时候考虑发布更小的模型，适合移动端的？

**Comment by ZhaoFancy** [comment]
目前暂时没有计划表，接下来有更新的话会回复你。

**Comment by LMR2018** [comment]
> 目前暂时没有计划表，接下来有更新的话会回复你。

如果我想训练自己的数据，某一行业的就够了，数据量几十万，能不能训练出一个比6B更小的模型出来？

**Comment by ZhaoFancy** [comment]
> > 目前暂时没有计划表，接下来有更新的话会回复你。
> 
> 如果我想训练自己的数据，某一行业的就够了，数据量几十万，能不能训练出一个比6B更小的模型出来？

这个问题 off topic 了，建议在 https://github.com/01-ai/Yi/discussions 里讨论。
