### ISSUE TITLE
34B模型转换后用megatron训练sft，效果不符合预期。

### ISSUE THREAD

**Issue by zhangmi0991** [01-ai/Yi#98]
我们基于01-ai开源的34B base model，转化后使用megatron进行 SFT（转化后的模型应该没什么问题，因为用相同方式转过llama模型，跑出sft模型效果是正常的），sft loss下降也正常，3 个 epoch 之后，loss 只有 0.2 左右，但效果不符合预期，比如在数学问题上，cot过程不如其他开源13B base模型sft之后的效果（其他开源的13B模型和01-ai 34B用的同一份sft数据训练的），目前排查不到具体原因，想了解一下还有其他因素会造成这种效果吗？

示例：
【prompt】
请回答一下问题，先一步一步分析，然后得到答案。\n服装加工厂5天生产西服750套,照这样计算,一个月(30天)生产西服多少套?

【yi-34B-sft】 
1. 确定每天的西装产量：根据题目给出的信息，工厂在一天内可以完成750套西装的生产任务。
2. 根据这个数据进行推算，一周（7个工作日）的产能为:  7 * 750 = 4950件。这里我们取整周的工作量作为基数以便于后期的月度产量的比较和计算。
3. 为了找到每月的生产力，我们将每周的数量除以每月的工作周数。由于一月有约36个星期四舍五入到最近的完整数目的话应该是38周零两天左右 (因为一年通常有52周但是减去元旦至春节期间的停产时间以及可能的停工等特殊情况)所以我们可以用以下公式计算出每个月的总容量: 
   每月产量=（4950×38）/36≈18万套 （保留三位小数为精确值，注意这里的单位是“套”不是 “件”）

因此，按照这种算法，这家工厂可以在一月份最多产出大约18万的西装套装。

【other-13B-model】
首先，我们可以将5天生产750套西服转换为每天生产的套数。用750除以5，我们得到每天生产150套西服。

接下来，我们需要计算一个月（30天）中每天生产西服的套数。用每天生产的150套西服乘以30天，我们得到一个月总共生产的西服套数：150 × 30 = 4500套。

所以，服装加工厂一个月（30天）生产西服4500套。

**Comment by ZhaoFancy** [comment]
可能的因素比较多。请问这个数据是开源的么？如果是的话，我们这边可以内部测试下。

**Comment by zhangmi0991** [comment]
我们用的数据是多个开源数据做了一些采样组合的（保证prompt多样性）。目前测试数学推理的时候会有这个明显的问题，你们现在有内测的34B chat model吗，可以试试这个case吗，如果回复结果正常，我们就再自查一下。

**Comment by ZhaoFancy** [comment]
以下是我们内部测试的结果，仅供参考。

```
好的，我们可以通过以下步骤来解决这个问题：

确定每天的生产量：首先，我们需要知道服装加工厂每天生产多少套西服。他们5天生产了750套西服，所以平均每天的产量是：

[ \frac{750套}{5天} = 150套/天 ]

计算一个月的总产量：现在我们知道每天生产150套西服，那么一个月（30天）可以生产多少套呢？我们可以用每天的产量乘以30天来得到：

[ 150套/天 \times 30天 = 4500套 ]

所以，服装加工厂一个月（30天）可以生产4500套西服。
```

**Comment by zhangmi0991** [comment]
了解了，我们再排查下。

**Comment by zhangmi0991** [comment]
> 以下是我们内部测试的结果，仅供参考。
> 
> ```
> 好的，我们可以通过以下步骤来解决这个问题：
> 
> 确定每天的生产量：首先，我们需要知道服装加工厂每天生产多少套西服。他们5天生产了750套西服，所以平均每天的产量是：
> 
> [ \frac{750套}{5天} = 150套/天 ]
> 
> 计算一个月的总产量：现在我们知道每天生产150套西服，那么一个月（30天）可以生产多少套呢？我们可以用每天的产量乘以30天来得到：
> 
> [ 150套/天 \times 30天 = 4500套 ]
> 
> 所以，服装加工厂一个月（30天）可以生产4500套西服。
> ```


你好
方便透露一下，这个结果的微调版本的learning rate是设置了多少吗

**Comment by ZhaoFancy** [comment]
> 方便透露一下，这个结果的微调版本的learning rate是设置了多少吗

抱歉这个可能没太有参考意义，具体 SFT 的细节 *可能* 会包含在最终的技术报告里。

**Comment by chenyzh28** [comment]
34B模型训练的配置是多少呢？单机8卡A800可以吗？

**Comment by ZhiningMa** [comment]
megatron的训练方式是怎么调整的，方便分享吗？
